/*
 * TutorTemplate.java
 *
 * Created on October 18, 2005, 5:33 PM
 */

package SimStFractionAdditionV1;

import edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Launcher;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;


/**
 * A template for Java-language student interfaces. For use with TutorTemplate.form and NetBeans v6.x.
 * @author  mpschnei
 */
public class SimStAlgebraV8 extends javax.swing.JPanel {
    
    /** Creates new form TutorTemplate */
    public SimStAlgebraV8() {
		setDefaultLookAndFeel();
        initComponents();
    }
    
	private void setDefaultLookAndFeel()
	{
		try {
			UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		} catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}
		
		UIManager.put("Label.font", new Font("Serif", Font.PLAIN, 16));
		UIManager.put("Button.font", new Font("Serif", Font.PLAIN, 16));
		UIManager.put("Button.highlight", Color.WHITE);
		UIManager.put("Button.foreground", Color.BLACK);
		UIManager.put("Button.background", new Color(209,217,225));
		UIManager.put("Button.disabledText", new Color(153,153,153));
	}
	
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cTAT_Options1 = new edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options();
        done = new pact.CommWidgets.JCommButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        dorminTable1 = new pact.CommWidgets.JCommTable();
        dorminTable2 = new pact.CommWidgets.JCommTable();
        dorminLabel1 = new pact.CommWidgets.JCommLabel();
        dorminLabel2 = new pact.CommWidgets.JCommLabel();
        dorminLabel3 = new pact.CommWidgets.JCommLabel();
        dorminLabel4 = new pact.CommWidgets.JCommLabel();
        dorminLabel5 = new pact.CommWidgets.JCommLabel();
        dorminLabel6 = new pact.CommWidgets.JCommLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        dorminTable3 = new pact.CommWidgets.JCommTable();

        setLayout(null);

		dorminTable1.setToolTipText("Enter the equation here. See Unit Overview for suggested problems.");
		dorminTable2.setToolTipText("Enter the equation here. See Unit Overview for suggested problems.");
		dorminTable3.setToolTipText("Enter the transformation here.");

        done.setText("Problem is Solved");
        done.setName("done");
        add(done);
        done.setBounds(10, 315, 540, 40);

        jLayeredPane1.setBackground(new java.awt.Color(235, 221, 195));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(), "Equation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jLayeredPane1.setForeground(new java.awt.Color(240, 240, 240));
        jLayeredPane1.setOpaque(true);

        dorminTable1.setName("dorminTable1");
        dorminTable1.setColumns(1);
        dorminTable1.setPreferredSize(new java.awt.Dimension(100, 250));
        dorminTable1.setRows(6);
        dorminTable1.setBounds(20, 40, 100, 245);
        jLayeredPane1.add(dorminTable1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dorminTable2.setName("dorminTable2");
        dorminTable2.setColumns(1);
        dorminTable2.setPreferredSize(new java.awt.Dimension(100, 250));
        dorminTable2.setRows(6);
        dorminTable2.setBounds(170, 40, 100, 245);
        jLayeredPane1.add(dorminTable2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dorminLabel1.setName("equals");
        dorminLabel1.setFont(new java.awt.Font("Verdana", 0, 24));
        dorminLabel1.setText("=");
        dorminLabel1.setBounds(130, 250, 20, 20);
        jLayeredPane1.add(dorminLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dorminLabel2.setFont(new java.awt.Font("Verdana", 0, 24));
        dorminLabel2.setText("=");
        dorminLabel2.setBounds(130, 50, 20, 20);
        jLayeredPane1.add(dorminLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dorminLabel3.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        dorminLabel3.setText("=");
        dorminLabel3.setBounds(130, 90, 20, 20);
        jLayeredPane1.add(dorminLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dorminLabel4.setFont(new java.awt.Font("Verdana", 0, 24));
        dorminLabel4.setText("=");
        dorminLabel4.setBounds(130, 130, 20, 20);
        jLayeredPane1.add(dorminLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dorminLabel5.setFont(new java.awt.Font("Verdana", 0, 24));
        dorminLabel5.setText("=");
        dorminLabel5.setBounds(130, 170, 20, 20);
        jLayeredPane1.add(dorminLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        dorminLabel6.setFont(new java.awt.Font("Verdana", 0, 24));
        dorminLabel6.setText("=");
        dorminLabel6.setBounds(130, 210, 20, 20);
        jLayeredPane1.add(dorminLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane1);
        jLayeredPane1.setBounds(0, 0, 290, 300);

        jLayeredPane2.setBackground(new java.awt.Color(192, 186, 186));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(), "Transformation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jLayeredPane2.setOpaque(true);

        dorminTable3.setName("dorminTable3");
        dorminTable3.setColumns(1);
        dorminTable3.setPreferredSize(new java.awt.Dimension(120, 250));
        dorminTable3.setRows(6);
        dorminTable3.setBounds(20, 40, 210, 250);
        jLayeredPane2.add(dorminTable3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        add(jLayeredPane2);
        jLayeredPane2.setBounds(300, 0, 250, 300);
    }// </editor-fold>//GEN-END:initComponents
    
    public static void main(String[] argv) {
       new CTAT_Launcher(argv).launch (new SimStAlgebraV8());  
        
   	
		
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options cTAT_Options1;
    private pact.CommWidgets.JCommButton done;
    private pact.CommWidgets.JCommLabel dorminLabel1;
    private pact.CommWidgets.JCommLabel dorminLabel2;
    private pact.CommWidgets.JCommLabel dorminLabel3;
    private pact.CommWidgets.JCommLabel dorminLabel4;
    private pact.CommWidgets.JCommLabel dorminLabel5;
    private pact.CommWidgets.JCommLabel dorminLabel6;
    private pact.CommWidgets.JCommTable dorminTable1;
    private pact.CommWidgets.JCommTable dorminTable2;
    private pact.CommWidgets.JCommTable dorminTable3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    // End of variables declaration//GEN-END:variables
    
}
