/*
 * TutorTemplate.java
 *
 * Created on October 18, 2005, 5:33 PM
 */

//  package TabbedPretest;

import edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Launcher;

/**
 * A template for Java-language student interfaces. For use with TutorTemplate.form and NetBeans v6.x.
 * @author  mpschnei
 */
public class MslqQuestionnaire extends javax.swing.JPanel {
    
    /** Creates new form TutorTemplate */
    public MslqQuestionnaire() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cTAT_Options1 = new edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options();
        jLabel1 = new javax.swing.JLabel();
        questionnaire_problem5 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        questionnaire_problem7 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        questionnaire_problem10 = new pact.DorminWidgets.DorminMultipleChoice();
        questionnaire_problem1 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        questionnaire_problem6 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        questionnaire_problem8 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        Done = new pact.DorminWidgets.DorminButton();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        questionnaire_problem2 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        questionnaire_problem3 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        questionnaire_problem4 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        questionnaire_problem9 = new pact.DorminWidgets.DorminMultipleChoice();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        promptSuccess = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        dorminLabel1 = new pact.DorminWidgets.DorminLabel();

        cTAT_Options1.setSeparateHintWindow(true);

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Review Questionnaire");

        questionnaire_problem5.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem5.setNChoices(7);
        questionnaire_problem5.setChoiceLayout(1);
        questionnaire_problem5.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem5.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem5.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem5.setQuestionText("");

        jLabel82.setText("Not at all true of me");

        jLabel83.setText("Very true of me");

        jLabel84.setText("Not at all true of me");

        jLabel85.setText("Sometimes True of Me");

        jLabel86.setText("Sometimes True of Me");

        jLabel87.setText("Sometimes True of Me");

        jLabel88.setText("Sometimes True of Me");

        jLabel89.setText("Very true of me");

        jLabel90.setText("Very true of me");

        questionnaire_problem7.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem7.setNChoices(7);
        questionnaire_problem7.setChoiceLayout(1);
        questionnaire_problem7.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem7.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem7.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem7.setQuestionText("");

        jLabel91.setText("Very true of me");

        jLabel92.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel92.setText("<HTML>7.  I tried to discover general patterns of equation solving from the examples. ");

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel93.setText("<HTML>10.  Pleas rate how easy it was to teach Lucy.");

        jLabel94.setText("So-So");

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel95.setText("<HTML>9.  I feel I'm a lot more confident in solving Algebraic equations now.");

        questionnaire_problem10.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem10.setNChoices(7);
        questionnaire_problem10.setChoiceLayout(1);
        questionnaire_problem10.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem10.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem10.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem10.setQuestionText("");

        questionnaire_problem1.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem1.setNChoices(7);
        questionnaire_problem1.setChoiceLayout(1);
        questionnaire_problem1.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem1.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem1.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem1.setQuestionText("");

        jLabel96.setText("Not at all true of me");

        jLabel97.setText("Not at all true of me");

        questionnaire_problem6.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem6.setNChoices(7);
        questionnaire_problem6.setChoiceLayout(1);
        questionnaire_problem6.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem6.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem6.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem6.setQuestionText("");

        jLabel98.setText("Sometimes True of Me");

        jLabel99.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel99.setText("<HTML>4.  I am very interested in Algebra and equations.");

        jLabel100.setText("Sometimes True of Me");

        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel101.setText("<HTML>5.  I have an uneasy, upset feeling when I take the pre/post tests.");

        jLabel102.setText("Very true of me");

        questionnaire_problem8.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem8.setNChoices(7);
        questionnaire_problem8.setChoiceLayout(1);
        questionnaire_problem8.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem8.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem8.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem8.setQuestionText("");

        jLabel103.setText("Very true of me");

        jLabel104.setText("Not at all true of me");

        Done.setCorrectColor(new java.awt.Color(0, 0, 0));
        Done.setIncorrectColor(new java.awt.Color(0, 0, 0));
        Done.setText("Complete Survey");
        Done.addStudentActionListener(new pact.DorminWidgets.event.StudentActionListener() {
            public void studentActionPerformed(pact.DorminWidgets.event.StudentActionEvent evt) {
                promptNow(evt);
            }
        });

        jLabel105.setText("Very Easy");

        jLabel106.setText("Sometimes True of Me");

        questionnaire_problem2.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem2.setNChoices(7);
        questionnaire_problem2.setChoiceLayout(1);
        questionnaire_problem2.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem2.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem2.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem2.setQuestionText("");

        jLabel107.setText("Not at all true of me");

        jLabel108.setText("Very Difficult");

        jLabel109.setText("Not at all true of me");

        jLabel110.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel110.setText("<HTML>8.  I think teaching Lucy is helpful for me in learning Algebraic equations. ");

        questionnaire_problem3.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem3.setNChoices(7);
        questionnaire_problem3.setChoiceLayout(1);
        questionnaire_problem3.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem3.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem3.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem3.setQuestionText("");

        jLabel111.setText("Very true of me");

        jLabel112.setText("Very true of me");

        jLabel113.setText("Not at all true of me");

        jLabel114.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel114.setText("<HTML>3.  I think I will be able to use what I learn in this course in other courses.");

        jLabel115.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel115.setText("<HTML>1.  My main concern in this Algebra class is getting a good grade.");

        jLabel116.setText("Not at all true of me");

        questionnaire_problem4.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem4.setNChoices(7);
        questionnaire_problem4.setChoiceLayout(1);
        questionnaire_problem4.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem4.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem4.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem4.setQuestionText("");

        jLabel117.setText("Sometimes True of Me");

        jLabel118.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel118.setText("<HTML>2.  In this Algebra class, I prefer course material that challenges me so I can learn new things.");

        jLabel119.setText("Very true of me");

        questionnaire_problem9.setBackground(new java.awt.Color(255, 255, 255));
        questionnaire_problem9.setNChoices(7);
        questionnaire_problem9.setChoiceLayout(1);
        questionnaire_problem9.setChoiceTexts("1,2,3,4,5,6,7");
        questionnaire_problem9.setCorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem9.setIncorrectColor(new java.awt.Color(0, 0, 0));
        questionnaire_problem9.setQuestionText("");

        jLabel120.setText("Sometimes True of Me");

        jLabel121.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel121.setText("<HTML>6.  By using the steps in the examples,  I managed to teach Lucy.");

        promptSuccess.setFont(new java.awt.Font("Tahoma", 1, 14));
        promptSuccess.setForeground(new java.awt.Color(0, 153, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("<HTML>For each of the following sentences, please click on one of the buttons on the 7-point scale to indicate whether or not a sentence is true of you. For example, if you think a sentence is quite true of you but not always true, you can indicate by clicking on 6, like so:");

        jLabel122.setText("Very true of me");

        jLabel123.setText("Not at all true of me");

        jLabel124.setText("Sometimes True of Me");

        dorminLabel1.setImageName("MslqQuestionnaire_example.png");
        dorminLabel1.setText("");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel114, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(jLabel99, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(jLabel101, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(jLabel115, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(202, 202, 202)
                                .add(Done, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel121, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(jLabel92, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(jLabel110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 536, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel93, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(106, 106, 106)
                                .add(promptSuccess, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(34, 34, 34)
                                .add(jLabel96)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(questionnaire_problem1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 312, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel91))
                            .add(jLabel95, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(234, 234, 234)
                                .add(jLabel98))
                            .add(jLabel118, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(36, 36, 36)
                                .add(jLabel107)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(questionnaire_problem2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 305, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel119))
                            .add(layout.createSequentialGroup()
                                .add(36, 36, 36)
                                .add(jLabel113)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(questionnaire_problem3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 296, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel89))
                            .add(layout.createSequentialGroup()
                                .add(240, 240, 240)
                                .add(jLabel86))
                            .add(layout.createSequentialGroup()
                                .add(232, 232, 232)
                                .add(jLabel106))
                            .add(layout.createSequentialGroup()
                                .add(33, 33, 33)
                                .add(jLabel116)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(questionnaire_problem4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 303, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel111))
                            .add(layout.createSequentialGroup()
                                .add(237, 237, 237)
                                .add(jLabel87))
                            .add(layout.createSequentialGroup()
                                .add(31, 31, 31)
                                .add(jLabel82)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(questionnaire_problem5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 311, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel83))
                            .add(layout.createSequentialGroup()
                                .add(240, 240, 240)
                                .add(jLabel117))
                            .add(layout.createSequentialGroup()
                                .add(33, 33, 33)
                                .add(jLabel97)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(questionnaire_problem6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 306, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel90))
                            .add(layout.createSequentialGroup()
                                .add(240, 240, 240)
                                .add(jLabel85))
                            .add(layout.createSequentialGroup()
                                .add(36, 36, 36)
                                .add(jLabel84)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(questionnaire_problem7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 307, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel112))
                            .add(layout.createSequentialGroup()
                                .add(242, 242, 242)
                                .add(jLabel88))
                            .add(layout.createSequentialGroup()
                                .add(33, 33, 33)
                                .add(jLabel104)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(questionnaire_problem8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 318, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel103))
                            .add(layout.createSequentialGroup()
                                .add(243, 243, 243)
                                .add(jLabel100))
                            .add(layout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(jLabel109)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(questionnaire_problem9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 318, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel102))
                            .add(layout.createSequentialGroup()
                                .add(244, 244, 244)
                                .add(jLabel120))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(layout.createSequentialGroup()
                                        .add(61, 61, 61)
                                        .add(jLabel108)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(questionnaire_problem10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 316, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                        .add(268, 268, 268)
                                        .add(jLabel94)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel105))
                            .add(jLabel2, 0, 0, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(jLabel123)
                        .add(18, 18, 18)
                        .add(dorminLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 283, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel122))
                    .add(layout.createSequentialGroup()
                        .add(220, 220, 220)
                        .add(jLabel124)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jLabel122))
                            .add(layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(dorminLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel124))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel123)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 39, Short.MAX_VALUE)
                .add(jLabel115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(jLabel96))
                    .add(layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(questionnaire_problem1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(jLabel91)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel98)
                .add(27, 27, 27)
                .add(jLabel118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(questionnaire_problem2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(jLabel107))
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jLabel119)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel106)
                .add(46, 46, 46)
                .add(jLabel114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(questionnaire_problem3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(35, 35, 35)
                        .add(jLabel89))
                    .add(layout.createSequentialGroup()
                        .add(38, 38, 38)
                        .add(jLabel113)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel86)
                .add(46, 46, 46)
                .add(jLabel99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(40, 40, 40)
                                .add(jLabel116))
                            .add(layout.createSequentialGroup()
                                .add(30, 30, 30)
                                .add(questionnaire_problem4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel87))
                    .add(layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(jLabel111)))
                .add(56, 56, 56)
                .add(jLabel101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(jLabel82))
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(questionnaire_problem5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel117))
                    .add(layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jLabel83)))
                .add(33, 33, 33)
                .add(jLabel121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(28, 28, 28)
                                .add(jLabel97))
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(questionnaire_problem6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel85))
                    .add(layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jLabel90)))
                .add(45, 45, 45)
                .add(jLabel92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(jLabel84))
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(questionnaire_problem7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel88))
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jLabel112)))
                .add(37, 37, 37)
                .add(jLabel110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(questionnaire_problem8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jLabel104))
                    .add(layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jLabel103)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel100)
                .add(53, 53, 53)
                .add(jLabel95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(questionnaire_problem9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(14, 14, 14)
                                .add(jLabel109)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel120))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel102)))
                .add(50, 50, 50)
                .add(jLabel93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(questionnaire_problem10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel94)
                                .add(79, 79, 79)
                                .add(Done, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(27, 27, 27)
                                .add(jLabel108)))
                        .add(30, 30, 30)
                        .add(promptSuccess, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jLabel105)))
                .add(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void promptNow(pact.DorminWidgets.event.StudentActionEvent evt) {//GEN-FIRST:event_promptNow
         promptSuccess.setText("Thank You For Completing the Survey!");
         Done.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_promptNow
    
    public static void main(String[] argv) {
        new CTAT_Launcher(argv).launch (new MslqQuestionnaire());
    }

    public java.awt.Dimension getPreferredSize()
    {
        return new java.awt.Dimension(618,2400);
        //java.awt.Toolkit tk = java.awt.Toolkit.getDefaultToolkit();
        //return new java.awt.Dimension(682, (int)((tk.getScreenSize().height)*0.8));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pact.DorminWidgets.DorminButton Done;
    private edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options cTAT_Options1;
    private pact.DorminWidgets.DorminLabel dorminLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JLabel promptSuccess;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem1;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem10;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem2;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem3;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem4;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem5;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem6;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem7;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem8;
    private pact.DorminWidgets.DorminMultipleChoice questionnaire_problem9;
    // End of variables declaration//GEN-END:variables
    
}
