/*

 * TutorTemplate.java

 *

 * Created on May 27, 2004, 10:27 PM

 */

package LogicTutor;




import java.awt.Component;

import java.awt.Container;

import java.lang.reflect.Field;

import java.util.StringTokenizer;



import javax.swing.JPanel;

import javax.swing.UIManager;

import javax.swing.UnsupportedLookAndFeelException;



import pact.CommWidgets.JCommWidget;

import edu.cmu.pact.Utilities.trace;

import edu.cmu.pact.BehaviorRecorder.Controller.BR_Controller;
import edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Launcher;

import edu.cmu.pact.BehaviorRecorder.Controller.BR_Controller;
import edu.cmu.pact.ctat.StudentInterfacePanel;





/**



 *



 * @author  sanket



 */







public class TruthTable extends JPanel  



						implements LogicExprParser.Listener, StudentInterfacePanel {



    



	/**



	 * Parser for logic expressions.



	 */



	private LogicExprParser logicExprParser = LogicExprParser.instance();







	/**



	 * Latest parse result received.



	 */



	private LogicExprParser.ParseEvent parseEvent = null;



    



    /** Creates new form TutorTemplate */



    public TruthTable() {



        super();



        



        initComponents();



        



        initialSetup();



		logicExprParser.addParseEventListener(this);



    }



    



    /** This method is called from within the constructor to



     * initialize the form.



     * WARNING: Do NOT modify this code. The content of this method is



     * always regenerated by the Form Editor.



     */



    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents



    private void initComponents() {



        cTAT_Options1 = new edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options();

        

        cTAT_Options1.setConnectToLispAtStartup(false);

        cTAT_Options1.setSeparateHintWindow(false);

        cTAT_Options1.setShowAdvanceProblemMenu(false);

        cTAT_Options1.setShowBehaviorRecorder(true);

        cTAT_Options1.setShowLoginWindow(false);

        cTAT_Options1.setUseExampleTracingTutor(false);

        cTAT_Options1.setUseJESSCognitiveTutor(true);



        commTextField1 = new pact.CommWidgets.JCommTextField();



        jTextArea2 = new javax.swing.JTextArea();



        switchablePanel = new javax.swing.JPanel();



        commTable1 = new pact.CommWidgets.JCommTable();



        chooseDonePanel = new javax.swing.JPanel();



        jTextArea1 = new javax.swing.JTextArea();



        jPanel1 = new javax.swing.JPanel();



        commRadioButton12 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton13 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton14 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton1 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton8 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton6 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton7 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton3 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton9 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton5 = new pact.CommWidgets.JCommRadioButton();



        commRadioButton15 = new pact.CommWidgets.JCommRadioButton();



        Hint = new pact.CommWidgets.JCommButton();



        Done = new pact.CommWidgets.JCommButton();



        dummyButton = new pact.CommWidgets.JCommRadioButton();



        headerPanel = new javax.swing.JPanel();



        commTextField2 = new pact.CommWidgets.JCommTextField();



        commTextField3 = new pact.CommWidgets.JCommTextField();



        commTextField4 = new pact.CommWidgets.JCommTextField();



        commTextField10 = new pact.CommWidgets.JCommTextField();



        commTextField11 = new pact.CommWidgets.JCommTextField();



        commTextField12 = new pact.CommWidgets.JCommTextField();



        commTextField5 = new pact.CommWidgets.JCommTextField();



        commTextField6 = new pact.CommWidgets.JCommTextField();



        commTextField7 = new pact.CommWidgets.JCommTextField();



        commTextField8 = new pact.CommWidgets.JCommTextField();



        commTextField13 = new pact.CommWidgets.JCommTextField();



        commTextField14 = new pact.CommWidgets.JCommTextField();



        commTextField9 = new pact.CommWidgets.JCommTextField();



        commTextField15 = new pact.CommWidgets.JCommTextField();



        commTextField16 = new pact.CommWidgets.JCommTextField();



        one_var = new javax.swing.JPanel();



        jTextField5 = new javax.swing.JTextField();



        jTextField7 = new javax.swing.JTextField();



        two_var = new javax.swing.JPanel();



        jTextField69 = new javax.swing.JTextField();



        jTextField70 = new javax.swing.JTextField();



        jTextField71 = new javax.swing.JTextField();



        jTextField72 = new javax.swing.JTextField();



        jTextField81 = new javax.swing.JTextField();



        jTextField82 = new javax.swing.JTextField();



        jTextField83 = new javax.swing.JTextField();



        jTextField84 = new javax.swing.JTextField();



        three_var = new javax.swing.JPanel();



        jTextField129 = new javax.swing.JTextField();



        jTextField130 = new javax.swing.JTextField();



        jTextField131 = new javax.swing.JTextField();



        jTextField132 = new javax.swing.JTextField();



        jTextField133 = new javax.swing.JTextField();



        jTextField134 = new javax.swing.JTextField();



        jTextField135 = new javax.swing.JTextField();



        jTextField136 = new javax.swing.JTextField();



        jTextField145 = new javax.swing.JTextField();



        jTextField146 = new javax.swing.JTextField();



        jTextField147 = new javax.swing.JTextField();



        jTextField148 = new javax.swing.JTextField();



        jTextField149 = new javax.swing.JTextField();



        jTextField150 = new javax.swing.JTextField();



        jTextField151 = new javax.swing.JTextField();



        jTextField152 = new javax.swing.JTextField();



        jTextField178 = new javax.swing.JTextField();



        jTextField180 = new javax.swing.JTextField();



        jTextField182 = new javax.swing.JTextField();



        jTextField184 = new javax.swing.JTextField();



        jTextField186 = new javax.swing.JTextField();



        jTextField188 = new javax.swing.JTextField();



        jTextField190 = new javax.swing.JTextField();



        jTextField192 = new javax.swing.JTextField();



        four_var = new javax.swing.JPanel();



        jTextField193 = new javax.swing.JTextField();



        jTextField194 = new javax.swing.JTextField();



        jTextField195 = new javax.swing.JTextField();



        jTextField196 = new javax.swing.JTextField();



        jTextField197 = new javax.swing.JTextField();



        jTextField198 = new javax.swing.JTextField();



        jTextField199 = new javax.swing.JTextField();



        jTextField200 = new javax.swing.JTextField();



        jTextField201 = new javax.swing.JTextField();



        jTextField202 = new javax.swing.JTextField();



        jTextField203 = new javax.swing.JTextField();



        jTextField204 = new javax.swing.JTextField();



        jTextField205 = new javax.swing.JTextField();



        jTextField206 = new javax.swing.JTextField();



        jTextField207 = new javax.swing.JTextField();



        jTextField208 = new javax.swing.JTextField();



        jTextField209 = new javax.swing.JTextField();



        jTextField210 = new javax.swing.JTextField();



        jTextField211 = new javax.swing.JTextField();



        jTextField212 = new javax.swing.JTextField();



        jTextField213 = new javax.swing.JTextField();



        jTextField214 = new javax.swing.JTextField();



        jTextField215 = new javax.swing.JTextField();



        jTextField216 = new javax.swing.JTextField();



        jTextField217 = new javax.swing.JTextField();



        jTextField218 = new javax.swing.JTextField();



        jTextField219 = new javax.swing.JTextField();



        jTextField220 = new javax.swing.JTextField();



        jTextField221 = new javax.swing.JTextField();



        jTextField222 = new javax.swing.JTextField();



        jTextField223 = new javax.swing.JTextField();



        jTextField224 = new javax.swing.JTextField();



        jTextField225 = new javax.swing.JTextField();



        jTextField226 = new javax.swing.JTextField();



        jTextField227 = new javax.swing.JTextField();



        jTextField228 = new javax.swing.JTextField();



        jTextField229 = new javax.swing.JTextField();



        jTextField230 = new javax.swing.JTextField();



        jTextField231 = new javax.swing.JTextField();



        jTextField232 = new javax.swing.JTextField();



        jTextField233 = new javax.swing.JTextField();



        jTextField234 = new javax.swing.JTextField();



        jTextField235 = new javax.swing.JTextField();



        jTextField236 = new javax.swing.JTextField();



        jTextField237 = new javax.swing.JTextField();



        jTextField238 = new javax.swing.JTextField();



        jTextField239 = new javax.swing.JTextField();



        jTextField240 = new javax.swing.JTextField();



        jTextField241 = new javax.swing.JTextField();



        jTextField242 = new javax.swing.JTextField();



        jTextField243 = new javax.swing.JTextField();



        jTextField244 = new javax.swing.JTextField();



        jTextField245 = new javax.swing.JTextField();



        jTextField246 = new javax.swing.JTextField();



        jTextField247 = new javax.swing.JTextField();



        jTextField248 = new javax.swing.JTextField();



        jTextField249 = new javax.swing.JTextField();



        jTextField250 = new javax.swing.JTextField();



        jTextField251 = new javax.swing.JTextField();



        jTextField252 = new javax.swing.JTextField();



        jTextField253 = new javax.swing.JTextField();



        jTextField254 = new javax.swing.JTextField();



        jTextField255 = new javax.swing.JTextField();



        jTextField256 = new javax.swing.JTextField();



        jButton1 = new javax.swing.JButton();







        cTAT_Options1.setSeparateHintWindow(true);
	add(cTAT_Options1);







        setLayout(null);







        commTextField1.setFont(new java.awt.Font("Dialog", 1, 18));



        commTextField1.setCommName("commTextField1");



        add(commTextField1);



        commTextField1.setBounds(20, 20, 1040, 30);







        jTextArea2.setEditable(false);



        jTextArea2.setFont(new java.awt.Font("Dialog", 0, 10));



        jTextArea2.setLineWrap(true);



        jTextArea2.setText("Sentential Logic Expression:");



        jTextArea2.setWrapStyleWord(true);



        add(jTextArea2);



        jTextArea2.setBounds(20, 0, 200, 20);







        switchablePanel.setLayout(null);







        switchablePanel.setName("switchablePanel");



        commTable1.setBackground(new java.awt.Color(255, 255, 255));



        commTable1.setFont(new java.awt.Font("Dialog", 0, 18));



        commTable1.setColumns(11);



        commTable1.setCorrectFont(new java.awt.Font("Dialog", 0, 18));



        commTable1.setCommName("commTable1");



        commTable1.setIncorrectFont(new java.awt.Font("Dialog", 0, 18));



        commTable1.setName("pcolumn");



        commTable1.setRows(16);



        commTable1.setOpaque(false);


		commTable1.setInvisible(true);
		

        switchablePanel.add(commTable1);



        commTable1.setBounds(203, 108, 850, 530);







        chooseDonePanel.setLayout(null);







        chooseDonePanel.setName("chooseDonePanel");



        jTextArea1.setEditable(false);



        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 10));



        jTextArea1.setLineWrap(true);



        jTextArea1.setText("Select the column that contains the answer:\n");



        jTextArea1.setWrapStyleWord(true);



        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));



        chooseDonePanel.add(jTextArea1);



        jTextArea1.setBounds(0, 30, 120, 30);







        jPanel1.setLayout(null);







        jPanel1.setBackground(new java.awt.Color(255, 255, 255));



        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));



        commRadioButton12.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton12.setCommName("commRadioButton12");



        commRadioButton12.setGroup("1");



        commRadioButton12.setText("^");



        jPanel1.add(commRadioButton12);



        commRadioButton12.setBounds(100, 3, 50, 22);







        commRadioButton13.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton13.setCommName("commRadioButton13");



        commRadioButton13.setGroup("1");



        commRadioButton13.setText("^");



        jPanel1.add(commRadioButton13);



        commRadioButton13.setBounds(180, 3, 40, 22);







        commRadioButton14.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton14.setCommName("commRadioButton14");



        commRadioButton14.setGroup("1");



        commRadioButton14.setText("^");



        jPanel1.add(commRadioButton14);



        commRadioButton14.setBounds(250, 3, 40, 22);







        commRadioButton1.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton1.setCommName("commRadioButton1");



        commRadioButton1.setGroup("1");



        commRadioButton1.setText("^");



        jPanel1.add(commRadioButton1);



        commRadioButton1.setBounds(330, 3, 40, 22);







        commRadioButton8.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton8.setCommName("commRadioButton8");



        commRadioButton8.setGroup("1");



        commRadioButton8.setText("^");



        jPanel1.add(commRadioButton8);



        commRadioButton8.setBounds(410, 3, 50, 22);







        commRadioButton6.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton6.setCommName("commRadioButton6");



        commRadioButton6.setGroup("1");



        commRadioButton6.setText("^");



        jPanel1.add(commRadioButton6);



        commRadioButton6.setBounds(480, 3, 40, 22);







        commRadioButton7.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton7.setCommName("commRadioButton7");



        commRadioButton7.setGroup("1");



        commRadioButton7.setText("^");



        jPanel1.add(commRadioButton7);



        commRadioButton7.setBounds(560, 3, 40, 22);







        commRadioButton3.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton3.setCommName("commRadioButton3");



        commRadioButton3.setGroup("1");



        commRadioButton3.setText("^");



        jPanel1.add(commRadioButton3);



        commRadioButton3.setBounds(640, 3, 40, 22);







        commRadioButton9.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton9.setCommName("commRadioButton9");



        commRadioButton9.setGroup("1");



        commRadioButton9.setText("^");



        jPanel1.add(commRadioButton9);



        commRadioButton9.setBounds(710, 3, 50, 22);







        commRadioButton5.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton5.setCommName("commRadioButton5");



        commRadioButton5.setGroup("1");



        commRadioButton5.setText("^");



        jPanel1.add(commRadioButton5);



        commRadioButton5.setBounds(790, 3, 40, 22);







        commRadioButton15.setBackground(new java.awt.Color(255, 255, 255));



        commRadioButton15.setCommName("commRadioButton15");



        commRadioButton15.setGroup("1");



        commRadioButton15.setText("^");



        commRadioButton15.setOpaque(false);



        jPanel1.add(commRadioButton15);



        commRadioButton15.setBounds(20, 3, 40, 22);







        chooseDonePanel.add(jPanel1);



        jPanel1.setBounds(0, 0, 850, 30);







        Hint.setCommName("Hint");



        Hint.setText("Hint");



        chooseDonePanel.add(Hint);



        Hint.setBounds(660, 40, 90, 40);







        Done.setCommName("Done");



        Done.setText("Done");



        chooseDonePanel.add(Done);



        Done.setBounds(760, 40, 90, 40);







        dummyButton.setBackground(new java.awt.Color(255, 255, 255));



        dummyButton.setCommName("dummyButton");



        dummyButton.setGroup("1");



        dummyButton.setName("dummyButton");



        dummyButton.setSelected(true);

		dummyButton.setInvisible(true);

        dummyButton.setOpaque(false);



        chooseDonePanel.add(dummyButton);



        dummyButton.setBounds(200, 40, 157, 22);







        switchablePanel.add(chooseDonePanel);



        chooseDonePanel.setBounds(203, 640, 1060, 140);







        headerPanel.setLayout(null);







        commTextField2.setCommName("commTextField2");



        headerPanel.add(commTextField2);



        commTextField2.setBounds(974, 3, 74, 50);







        commTextField3.setCommName("commTextField3");



        headerPanel.add(commTextField3);



        commTextField3.setBounds(896, 3, 74, 50);







        commTextField4.setCommName("commTextField4");



        headerPanel.add(commTextField4);



        commTextField4.setBounds(819, 3, 74, 50);







        commTextField10.setCommName("commTextField10");



        headerPanel.add(commTextField10);



        commTextField10.setBounds(742, 3, 74, 50);







        commTextField11.setCommName("commTextField11");



        headerPanel.add(commTextField11);



        commTextField11.setBounds(665, 3, 74, 50);







        commTextField12.setCommName("commTextField12");



        headerPanel.add(commTextField12);



        commTextField12.setBounds(588, 3, 74, 50);







        commTextField5.setCommName("commTextField5");



        headerPanel.add(commTextField5);



        commTextField5.setBounds(511, 3, 74, 50);







        commTextField6.setCommName("commTextField6");



        headerPanel.add(commTextField6);



        commTextField6.setBounds(434, 3, 74, 50);







        commTextField7.setCommName("commTextField7");



        headerPanel.add(commTextField7);



        commTextField7.setBounds(357, 3, 74, 50);







        commTextField8.setCommName("commTextField8");



        headerPanel.add(commTextField8);



        commTextField8.setBounds(280, 3, 74, 50);







        commTextField13.setCommName("commTextField13");



        headerPanel.add(commTextField13);



        commTextField13.setBounds(203, 3, 74, 50);







        commTextField14.setCommName("commTextField14");



        headerPanel.add(commTextField14);



        commTextField14.setBounds(159, 3, 38, 50);







        commTextField9.setCommName("commTextField9");



        headerPanel.add(commTextField9);



        commTextField9.setBounds(119, 3, 38, 50);







        commTextField15.setCommName("commTextField15");



        headerPanel.add(commTextField15);



        commTextField15.setBounds(79, 3, 38, 50);







        commTextField16.setCommName("commTextField16");



        headerPanel.add(commTextField16);



        commTextField16.setBounds(39, 3, 38, 50);







        switchablePanel.add(headerPanel);



        headerPanel.setBounds(0, 50, 1110, 55);







        one_var.setLayout(null);







        jTextField5.setEditable(false);



        jTextField5.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField5.setText("  T");



        jTextField5.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField5.setPreferredSize(new java.awt.Dimension(63, 25));



        one_var.add(jTextField5);



        jTextField5.setBounds(160, 4, 37, 29);







        jTextField7.setEditable(false);



        jTextField7.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField7.setText("  F");



        jTextField7.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField7.setPreferredSize(new java.awt.Dimension(63, 25));



        one_var.add(jTextField7);



        jTextField7.setBounds(160, 37, 37, 29);







        switchablePanel.add(one_var);



        one_var.setBounds(0, 105, 200, 70);







        two_var.setLayout(null);







        jTextField69.setEditable(false);



        jTextField69.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField69.setText("  T");



        jTextField69.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField69.setPreferredSize(new java.awt.Dimension(63, 25));



        two_var.add(jTextField69);



        jTextField69.setBounds(160, 4, 37, 29);







        jTextField70.setEditable(false);



        jTextField70.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField70.setText("  F");



        jTextField70.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField70.setPreferredSize(new java.awt.Dimension(63, 25));



        two_var.add(jTextField70);



        jTextField70.setBounds(160, 104, 37, 29);







        jTextField71.setEditable(false);



        jTextField71.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField71.setText("  F");



        jTextField71.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField71.setPreferredSize(new java.awt.Dimension(63, 25));



        two_var.add(jTextField71);



        jTextField71.setBounds(160, 37, 37, 29);







        jTextField72.setEditable(false);



        jTextField72.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField72.setText("  T");



        jTextField72.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField72.setPreferredSize(new java.awt.Dimension(63, 25));



        two_var.add(jTextField72);



        jTextField72.setBounds(160, 70, 37, 29);







        jTextField81.setEditable(false);



        jTextField81.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField81.setText("  T");



        jTextField81.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField81.setPreferredSize(new java.awt.Dimension(63, 25));



        two_var.add(jTextField81);



        jTextField81.setBounds(120, 4, 37, 29);







        jTextField82.setEditable(false);



        jTextField82.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField82.setText("  T");



        jTextField82.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField82.setPreferredSize(new java.awt.Dimension(63, 25));



        two_var.add(jTextField82);



        jTextField82.setBounds(120, 37, 37, 29);







        jTextField83.setEditable(false);



        jTextField83.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField83.setText("  F");



        jTextField83.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField83.setPreferredSize(new java.awt.Dimension(63, 25));



        two_var.add(jTextField83);



        jTextField83.setBounds(120, 104, 37, 29);







        jTextField84.setEditable(false);



        jTextField84.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField84.setText("  F");



        jTextField84.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField84.setPreferredSize(new java.awt.Dimension(63, 25));



        two_var.add(jTextField84);



        jTextField84.setBounds(120, 70, 37, 29);







        switchablePanel.add(two_var);



        two_var.setBounds(0, 105, 200, 135);







        three_var.setLayout(null);







        jTextField129.setEditable(false);



        jTextField129.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField129.setText("  T");



        jTextField129.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField129.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField129);



        jTextField129.setBounds(160, 137, 37, 29);







        jTextField130.setEditable(false);



        jTextField130.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField130.setText("  F");



        jTextField130.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField130.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField130);



        jTextField130.setBounds(160, 236, 37, 29);







        jTextField131.setEditable(false);



        jTextField131.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField131.setText("  F");



        jTextField131.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField131.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField131);



        jTextField131.setBounds(160, 170, 37, 29);







        jTextField132.setEditable(false);



        jTextField132.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField132.setText("  T");



        jTextField132.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField132.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField132);



        jTextField132.setBounds(160, 203, 37, 29);







        jTextField133.setEditable(false);



        jTextField133.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField133.setText("  T");



        jTextField133.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField133.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField133);



        jTextField133.setBounds(160, 4, 37, 29);







        jTextField134.setEditable(false);



        jTextField134.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField134.setText("  F");



        jTextField134.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField134.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField134);



        jTextField134.setBounds(160, 104, 37, 29);







        jTextField135.setEditable(false);



        jTextField135.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField135.setText("  F");



        jTextField135.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField135.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField135);



        jTextField135.setBounds(160, 37, 37, 29);







        jTextField136.setEditable(false);



        jTextField136.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField136.setText("  T");



        jTextField136.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField136.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField136);



        jTextField136.setBounds(160, 70, 37, 29);







        jTextField145.setEditable(false);



        jTextField145.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField145.setText("  T");



        jTextField145.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField145.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField145);



        jTextField145.setBounds(120, 4, 37, 29);







        jTextField146.setEditable(false);



        jTextField146.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField146.setText("  T");



        jTextField146.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField146.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField146);



        jTextField146.setBounds(120, 37, 37, 29);







        jTextField147.setEditable(false);



        jTextField147.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField147.setText("  F");



        jTextField147.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField147.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField147);



        jTextField147.setBounds(120, 104, 37, 29);







        jTextField148.setEditable(false);



        jTextField148.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField148.setText("  F");



        jTextField148.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField148.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField148);



        jTextField148.setBounds(120, 70, 37, 29);







        jTextField149.setEditable(false);



        jTextField149.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField149.setText("  F");



        jTextField149.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField149.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField149);



        jTextField149.setBounds(120, 203, 37, 29);







        jTextField150.setEditable(false);



        jTextField150.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField150.setText("  T");



        jTextField150.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField150.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField150);



        jTextField150.setBounds(120, 170, 37, 29);







        jTextField151.setEditable(false);



        jTextField151.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField151.setText("  T");



        jTextField151.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField151.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField151);



        jTextField151.setBounds(120, 137, 37, 29);







        jTextField152.setEditable(false);



        jTextField152.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField152.setText("  F");



        jTextField152.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField152.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField152);



        jTextField152.setBounds(120, 236, 37, 29);







        jTextField178.setEditable(false);



        jTextField178.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField178.setText("  F");



        jTextField178.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField178.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField178);



        jTextField178.setBounds(80, 236, 37, 29);







        jTextField180.setEditable(false);



        jTextField180.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField180.setText("  F");



        jTextField180.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField180.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField180);



        jTextField180.setBounds(80, 203, 37, 29);







        jTextField182.setEditable(false);



        jTextField182.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField182.setText("  F");



        jTextField182.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField182.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField182);



        jTextField182.setBounds(80, 170, 37, 29);







        jTextField184.setEditable(false);



        jTextField184.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField184.setText("  F");



        jTextField184.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField184.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField184);



        jTextField184.setBounds(80, 137, 37, 29);







        jTextField186.setEditable(false);



        jTextField186.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField186.setText("  T");



        jTextField186.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField186.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField186);



        jTextField186.setBounds(80, 104, 37, 29);







        jTextField188.setEditable(false);



        jTextField188.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField188.setText("  T");



        jTextField188.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField188.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField188);



        jTextField188.setBounds(80, 70, 37, 29);







        jTextField190.setEditable(false);



        jTextField190.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField190.setText("  T");



        jTextField190.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField190.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField190);



        jTextField190.setBounds(80, 37, 37, 29);







        jTextField192.setEditable(false);



        jTextField192.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField192.setText("  T");



        jTextField192.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField192.setPreferredSize(new java.awt.Dimension(63, 25));



        three_var.add(jTextField192);



        jTextField192.setBounds(80, 4, 37, 29);







        switchablePanel.add(three_var);



        three_var.setBounds(0, 105, 200, 270);







        four_var.setLayout(null);







        jTextField193.setEditable(false);



        jTextField193.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField193.setText("  T");



        jTextField193.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField193.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField193);



        jTextField193.setBounds(160, 137, 37, 29);







        jTextField194.setEditable(false);



        jTextField194.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField194.setText("  F");



        jTextField194.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField194.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField194);



        jTextField194.setBounds(160, 236, 37, 29);







        jTextField195.setEditable(false);



        jTextField195.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField195.setText("  F");



        jTextField195.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField195.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField195);



        jTextField195.setBounds(160, 170, 37, 29);







        jTextField196.setEditable(false);



        jTextField196.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField196.setText("  T");



        jTextField196.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField196.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField196);



        jTextField196.setBounds(160, 203, 37, 29);







        jTextField197.setEditable(false);



        jTextField197.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField197.setText("  T");



        jTextField197.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField197.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField197);



        jTextField197.setBounds(160, 4, 37, 29);







        jTextField198.setEditable(false);



        jTextField198.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField198.setText("  F");



        jTextField198.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField198.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField198);



        jTextField198.setBounds(160, 104, 37, 29);







        jTextField199.setEditable(false);



        jTextField199.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField199.setText("  F");



        jTextField199.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField199.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField199);



        jTextField199.setBounds(160, 37, 37, 29);







        jTextField200.setEditable(false);



        jTextField200.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField200.setText("  T");



        jTextField200.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField200.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField200);



        jTextField200.setBounds(160, 70, 37, 29);







        jTextField201.setEditable(false);



        jTextField201.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField201.setText("  F");



        jTextField201.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField201.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField201);



        jTextField201.setBounds(160, 500, 37, 29);







        jTextField202.setEditable(false);



        jTextField202.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField202.setText("  T");



        jTextField202.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField202.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField202);



        jTextField202.setBounds(160, 466, 37, 29);







        jTextField203.setEditable(false);



        jTextField203.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField203.setText("  F");



        jTextField203.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField203.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField203);



        jTextField203.setBounds(160, 433, 37, 29);







        jTextField204.setEditable(false);



        jTextField204.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField204.setText("  T");



        jTextField204.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField204.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField204);



        jTextField204.setBounds(160, 400, 37, 29);







        jTextField205.setEditable(false);



        jTextField205.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField205.setText("  F");



        jTextField205.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField205.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField205);



        jTextField205.setBounds(160, 367, 37, 29);







        jTextField206.setEditable(false);



        jTextField206.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField206.setText("  T");



        jTextField206.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField206.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField206);



        jTextField206.setBounds(160, 334, 37, 29);







        jTextField207.setEditable(false);



        jTextField207.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField207.setText("  F");



        jTextField207.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField207.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField207);



        jTextField207.setBounds(160, 301, 37, 29);







        jTextField208.setEditable(false);



        jTextField208.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField208.setText("  T");



        jTextField208.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField208.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField208);



        jTextField208.setBounds(160, 269, 37, 29);







        jTextField209.setEditable(false);



        jTextField209.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField209.setText("  T");



        jTextField209.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField209.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField209);



        jTextField209.setBounds(120, 4, 37, 29);







        jTextField210.setEditable(false);



        jTextField210.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField210.setText("  T");



        jTextField210.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField210.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField210);



        jTextField210.setBounds(120, 37, 37, 29);







        jTextField211.setEditable(false);



        jTextField211.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField211.setText("  F");



        jTextField211.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField211.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField211);



        jTextField211.setBounds(120, 104, 37, 29);







        jTextField212.setEditable(false);



        jTextField212.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField212.setText("  F");



        jTextField212.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField212.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField212);



        jTextField212.setBounds(120, 70, 37, 29);







        jTextField213.setEditable(false);



        jTextField213.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField213.setText("  F");



        jTextField213.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField213.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField213);



        jTextField213.setBounds(120, 203, 37, 29);







        jTextField214.setEditable(false);



        jTextField214.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField214.setText("  T");



        jTextField214.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField214.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField214);



        jTextField214.setBounds(120, 170, 37, 29);







        jTextField215.setEditable(false);



        jTextField215.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField215.setText("  T");



        jTextField215.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField215.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField215);



        jTextField215.setBounds(120, 137, 37, 29);







        jTextField216.setEditable(false);



        jTextField216.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField216.setText("  F");



        jTextField216.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField216.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField216);



        jTextField216.setBounds(120, 236, 37, 29);







        jTextField217.setEditable(false);



        jTextField217.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField217.setText("  T");



        jTextField217.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField217.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField217);



        jTextField217.setBounds(120, 269, 37, 29);







        jTextField218.setEditable(false);



        jTextField218.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField218.setText("  T");



        jTextField218.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField218.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField218);



        jTextField218.setBounds(120, 301, 37, 29);







        jTextField219.setEditable(false);



        jTextField219.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField219.setText("  F");



        jTextField219.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField219.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField219);



        jTextField219.setBounds(120, 334, 37, 29);







        jTextField220.setEditable(false);



        jTextField220.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField220.setText("  F");



        jTextField220.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField220.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField220);



        jTextField220.setBounds(120, 367, 37, 29);







        jTextField221.setEditable(false);



        jTextField221.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField221.setText("  T");



        jTextField221.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField221.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField221);



        jTextField221.setBounds(120, 400, 37, 29);







        jTextField222.setEditable(false);



        jTextField222.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField222.setText("  T");



        jTextField222.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField222.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField222);



        jTextField222.setBounds(120, 433, 37, 29);







        jTextField223.setEditable(false);



        jTextField223.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField223.setText("  F");



        jTextField223.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField223.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField223);



        jTextField223.setBounds(120, 466, 37, 29);







        jTextField224.setEditable(false);



        jTextField224.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField224.setText("  F");



        jTextField224.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField224.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField224);



        jTextField224.setBounds(120, 500, 37, 29);







        jTextField225.setEditable(false);



        jTextField225.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField225.setText("  F");



        jTextField225.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField225.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField225);



        jTextField225.setBounds(80, 500, 37, 29);







        jTextField226.setEditable(false);



        jTextField226.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField226.setText("  F");



        jTextField226.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField226.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField226);



        jTextField226.setBounds(40, 500, 37, 29);







        jTextField227.setEditable(false);



        jTextField227.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField227.setText("  F");



        jTextField227.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField227.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField227);



        jTextField227.setBounds(40, 466, 37, 29);







        jTextField228.setEditable(false);



        jTextField228.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField228.setText("  F");



        jTextField228.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField228.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField228);



        jTextField228.setBounds(80, 466, 37, 29);







        jTextField229.setEditable(false);



        jTextField229.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField229.setText("  F");



        jTextField229.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField229.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField229);



        jTextField229.setBounds(40, 433, 37, 29);







        jTextField230.setEditable(false);



        jTextField230.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField230.setText("  F");



        jTextField230.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField230.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField230);



        jTextField230.setBounds(80, 433, 37, 29);







        jTextField231.setEditable(false);



        jTextField231.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField231.setText("  F");



        jTextField231.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField231.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField231);



        jTextField231.setBounds(40, 400, 37, 29);







        jTextField232.setEditable(false);



        jTextField232.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField232.setText("  F");



        jTextField232.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField232.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField232);



        jTextField232.setBounds(80, 400, 37, 29);







        jTextField233.setEditable(false);



        jTextField233.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField233.setText("  F");



        jTextField233.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField233.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField233);



        jTextField233.setBounds(40, 367, 37, 29);







        jTextField234.setEditable(false);



        jTextField234.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField234.setText("  T");



        jTextField234.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField234.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField234);



        jTextField234.setBounds(80, 367, 37, 29);







        jTextField235.setEditable(false);



        jTextField235.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField235.setText("  F");



        jTextField235.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField235.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField235);



        jTextField235.setBounds(40, 334, 37, 29);







        jTextField236.setEditable(false);



        jTextField236.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField236.setText("  T");



        jTextField236.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField236.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField236);



        jTextField236.setBounds(80, 334, 37, 29);







        jTextField237.setEditable(false);



        jTextField237.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField237.setText("  F");



        jTextField237.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField237.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField237);



        jTextField237.setBounds(40, 301, 37, 29);







        jTextField238.setEditable(false);



        jTextField238.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField238.setText("  T");



        jTextField238.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField238.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField238);



        jTextField238.setBounds(80, 301, 37, 29);







        jTextField239.setEditable(false);



        jTextField239.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField239.setText("  F");



        jTextField239.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField239.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField239);



        jTextField239.setBounds(40, 269, 37, 29);







        jTextField240.setEditable(false);



        jTextField240.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField240.setText("  T");



        jTextField240.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField240.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField240);



        jTextField240.setBounds(80, 269, 37, 29);







        jTextField241.setEditable(false);



        jTextField241.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField241.setText("  T");



        jTextField241.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField241.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField241);



        jTextField241.setBounds(40, 236, 37, 29);







        jTextField242.setEditable(false);



        jTextField242.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField242.setText("  F");



        jTextField242.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField242.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField242);



        jTextField242.setBounds(80, 236, 37, 29);







        jTextField243.setEditable(false);



        jTextField243.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField243.setText("  T");



        jTextField243.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField243.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField243);



        jTextField243.setBounds(40, 203, 37, 29);







        jTextField244.setEditable(false);



        jTextField244.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField244.setText("  F");



        jTextField244.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField244.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField244);



        jTextField244.setBounds(80, 203, 37, 29);







        jTextField245.setEditable(false);



        jTextField245.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField245.setText("  T");



        jTextField245.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField245.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField245);



        jTextField245.setBounds(40, 170, 37, 29);







        jTextField246.setEditable(false);



        jTextField246.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField246.setText("  F");



        jTextField246.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField246.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField246);



        jTextField246.setBounds(80, 170, 37, 29);







        jTextField247.setEditable(false);



        jTextField247.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField247.setText("  T");



        jTextField247.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField247.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField247);



        jTextField247.setBounds(40, 137, 37, 29);







        jTextField248.setEditable(false);



        jTextField248.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField248.setText("  F");



        jTextField248.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField248.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField248);



        jTextField248.setBounds(80, 137, 37, 29);







        jTextField249.setEditable(false);



        jTextField249.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField249.setText("  T");



        jTextField249.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField249.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField249);



        jTextField249.setBounds(40, 104, 37, 29);







        jTextField250.setEditable(false);



        jTextField250.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField250.setText("  T");



        jTextField250.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField250.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField250);



        jTextField250.setBounds(80, 104, 37, 29);







        jTextField251.setEditable(false);



        jTextField251.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField251.setText("  T");



        jTextField251.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField251.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField251);



        jTextField251.setBounds(40, 70, 37, 29);







        jTextField252.setEditable(false);



        jTextField252.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField252.setText("  T");



        jTextField252.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField252.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField252);



        jTextField252.setBounds(80, 70, 37, 29);







        jTextField253.setEditable(false);



        jTextField253.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField253.setText("  T");



        jTextField253.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField253.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField253);



        jTextField253.setBounds(40, 37, 37, 29);







        jTextField254.setEditable(false);



        jTextField254.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField254.setText("  T");



        jTextField254.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField254.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField254);



        jTextField254.setBounds(80, 37, 37, 29);







        jTextField255.setEditable(false);



        jTextField255.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField255.setText("  T");



        jTextField255.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField255.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField255);



        jTextField255.setBounds(40, 4, 37, 29);







        jTextField256.setEditable(false);



        jTextField256.setFont(new java.awt.Font("Dialog", 1, 18));



        jTextField256.setText("  T");



        jTextField256.setMinimumSize(new java.awt.Dimension(4, 25));



        jTextField256.setPreferredSize(new java.awt.Dimension(63, 25));



        four_var.add(jTextField256);



        jTextField256.setBounds(80, 4, 37, 29);







        switchablePanel.add(four_var);



        four_var.setBounds(0, 105, 200, 530);







        add(switchablePanel);



        switchablePanel.setBounds(0, 10, 1090, 770);







        jButton1.setFont(new java.awt.Font("Dialog", 0, 10));



        jButton1.setText("Start Over");



        jButton1.addActionListener(new java.awt.event.ActionListener() {



            public void actionPerformed(java.awt.event.ActionEvent evt) {



                startoverclick(evt);



            }



        });







        add(jButton1);



        jButton1.setBounds(260, 0, 100, 20);







    }



    // </editor-fold>//GEN-END:initComponents







    private void startoverclick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startoverclick

    //	System.out.println("From Truthtable -> goToStartState");
        controller.goToStartState();



    }//GEN-LAST:event_startoverclick



    



    /**







	/**



	 * Command-line syntax help.



	 */



	public static final String usageMsg =



		"Usage:\n" +



		"java [-Dtrace=<debugCode>[,...]] tutors.LogicTutor.TruthTable\n" +



		"where--\n" +



		"  -Dtrace=<debugCode>  means turn on debugging for trace code <debugCode>.\n";







	/**



	 * Command-line options: see {@link #usageMsg}.



	 *



     * @param args the command line arguments



     */



    public static void main(String args[]) {


/*
		try {



			String traceProps = System.getProperty("trace", "");



			StringTokenizer tkzr = new StringTokenizer(traceProps, ", ");



			while (tkzr.hasMoreTokens()) {



				String tkn = tkzr.nextToken();



				trace.addDebugCode(tkn);



			}



		} catch (SecurityException se) {



			System.err.println("Access to trace property denied: " + se);



			se.printStackTrace();



		}

*/

                TruthTable tt = new TruthTable();



                CTAT_Launcher launcher = new CTAT_Launcher(args);



         //       tt.controller = launcher.getController();



		launcher.launch (tt);



    }



    private BR_Controller controller;



    // Variables declaration - do not modify//GEN-BEGIN:variables



    private pact.CommWidgets.JCommButton Done;



    private pact.CommWidgets.JCommButton Hint;



    private edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options cTAT_Options1;



    private javax.swing.JPanel chooseDonePanel;



    private pact.CommWidgets.JCommRadioButton commRadioButton1;



    private pact.CommWidgets.JCommRadioButton commRadioButton12;



    private pact.CommWidgets.JCommRadioButton commRadioButton13;



    private pact.CommWidgets.JCommRadioButton commRadioButton14;



    private pact.CommWidgets.JCommRadioButton commRadioButton15;



    private pact.CommWidgets.JCommRadioButton commRadioButton3;



    private pact.CommWidgets.JCommRadioButton commRadioButton5;



    private pact.CommWidgets.JCommRadioButton commRadioButton6;



    private pact.CommWidgets.JCommRadioButton commRadioButton7;



    private pact.CommWidgets.JCommRadioButton commRadioButton8;



    private pact.CommWidgets.JCommRadioButton commRadioButton9;



    private pact.CommWidgets.JCommTable commTable1;



    private pact.CommWidgets.JCommTextField commTextField1;



    private pact.CommWidgets.JCommTextField commTextField10;



    private pact.CommWidgets.JCommTextField commTextField11;



    private pact.CommWidgets.JCommTextField commTextField12;



    private pact.CommWidgets.JCommTextField commTextField13;



    private pact.CommWidgets.JCommTextField commTextField14;



    private pact.CommWidgets.JCommTextField commTextField15;



    private pact.CommWidgets.JCommTextField commTextField16;



    private pact.CommWidgets.JCommTextField commTextField2;



    private pact.CommWidgets.JCommTextField commTextField3;



    private pact.CommWidgets.JCommTextField commTextField4;



    private pact.CommWidgets.JCommTextField commTextField5;



    private pact.CommWidgets.JCommTextField commTextField6;



    private pact.CommWidgets.JCommTextField commTextField7;



    private pact.CommWidgets.JCommTextField commTextField8;



    private pact.CommWidgets.JCommTextField commTextField9;



    private pact.CommWidgets.JCommRadioButton dummyButton;



    private javax.swing.JPanel four_var;



    private javax.swing.JPanel headerPanel;



    private javax.swing.JButton jButton1;



    private javax.swing.JPanel jPanel1;



    private javax.swing.JTextArea jTextArea1;



    private javax.swing.JTextArea jTextArea2;



    private javax.swing.JTextField jTextField129;



    private javax.swing.JTextField jTextField130;



    private javax.swing.JTextField jTextField131;



    private javax.swing.JTextField jTextField132;



    private javax.swing.JTextField jTextField133;



    private javax.swing.JTextField jTextField134;



    private javax.swing.JTextField jTextField135;



    private javax.swing.JTextField jTextField136;



    private javax.swing.JTextField jTextField145;



    private javax.swing.JTextField jTextField146;



    private javax.swing.JTextField jTextField147;



    private javax.swing.JTextField jTextField148;



    private javax.swing.JTextField jTextField149;



    private javax.swing.JTextField jTextField150;



    private javax.swing.JTextField jTextField151;



    private javax.swing.JTextField jTextField152;



    private javax.swing.JTextField jTextField178;



    private javax.swing.JTextField jTextField180;



    private javax.swing.JTextField jTextField182;



    private javax.swing.JTextField jTextField184;



    private javax.swing.JTextField jTextField186;



    private javax.swing.JTextField jTextField188;



    private javax.swing.JTextField jTextField190;



    private javax.swing.JTextField jTextField192;



    private javax.swing.JTextField jTextField193;



    private javax.swing.JTextField jTextField194;



    private javax.swing.JTextField jTextField195;



    private javax.swing.JTextField jTextField196;



    private javax.swing.JTextField jTextField197;



    private javax.swing.JTextField jTextField198;



    private javax.swing.JTextField jTextField199;



    private javax.swing.JTextField jTextField200;



    private javax.swing.JTextField jTextField201;



    private javax.swing.JTextField jTextField202;



    private javax.swing.JTextField jTextField203;



    private javax.swing.JTextField jTextField204;



    private javax.swing.JTextField jTextField205;



    private javax.swing.JTextField jTextField206;



    private javax.swing.JTextField jTextField207;



    private javax.swing.JTextField jTextField208;



    private javax.swing.JTextField jTextField209;



    private javax.swing.JTextField jTextField210;



    private javax.swing.JTextField jTextField211;



    private javax.swing.JTextField jTextField212;



    private javax.swing.JTextField jTextField213;



    private javax.swing.JTextField jTextField214;



    private javax.swing.JTextField jTextField215;



    private javax.swing.JTextField jTextField216;



    private javax.swing.JTextField jTextField217;



    private javax.swing.JTextField jTextField218;



    private javax.swing.JTextField jTextField219;



    private javax.swing.JTextField jTextField220;



    private javax.swing.JTextField jTextField221;



    private javax.swing.JTextField jTextField222;



    private javax.swing.JTextField jTextField223;



    private javax.swing.JTextField jTextField224;



    private javax.swing.JTextField jTextField225;



    private javax.swing.JTextField jTextField226;



    private javax.swing.JTextField jTextField227;



    private javax.swing.JTextField jTextField228;



    private javax.swing.JTextField jTextField229;



    private javax.swing.JTextField jTextField230;



    private javax.swing.JTextField jTextField231;



    private javax.swing.JTextField jTextField232;



    private javax.swing.JTextField jTextField233;



    private javax.swing.JTextField jTextField234;



    private javax.swing.JTextField jTextField235;



    private javax.swing.JTextField jTextField236;



    private javax.swing.JTextField jTextField237;



    private javax.swing.JTextField jTextField238;



    private javax.swing.JTextField jTextField239;



    private javax.swing.JTextField jTextField240;



    private javax.swing.JTextField jTextField241;



    private javax.swing.JTextField jTextField242;



    private javax.swing.JTextField jTextField243;



    private javax.swing.JTextField jTextField244;



    private javax.swing.JTextField jTextField245;



    private javax.swing.JTextField jTextField246;



    private javax.swing.JTextField jTextField247;



    private javax.swing.JTextField jTextField248;



    private javax.swing.JTextField jTextField249;



    private javax.swing.JTextField jTextField250;



    private javax.swing.JTextField jTextField251;



    private javax.swing.JTextField jTextField252;



    private javax.swing.JTextField jTextField253;



    private javax.swing.JTextField jTextField254;



    private javax.swing.JTextField jTextField255;



    private javax.swing.JTextField jTextField256;



    private javax.swing.JTextField jTextField5;



    private javax.swing.JTextField jTextField69;



    private javax.swing.JTextField jTextField7;



    private javax.swing.JTextField jTextField70;



    private javax.swing.JTextField jTextField71;



    private javax.swing.JTextField jTextField72;



    private javax.swing.JTextField jTextField81;



    private javax.swing.JTextField jTextField82;



    private javax.swing.JTextField jTextField83;



    private javax.swing.JTextField jTextField84;



    private javax.swing.JPanel one_var;



    private javax.swing.JPanel switchablePanel;



    private javax.swing.JPanel three_var;



    private javax.swing.JPanel two_var;



    // End of variables declaration//GEN-END:variables



	







	/**



	 * Called when a parse() attempt has been completed. Calls



	 * {@link #redrawForNewVariableCount(int)} if parse succeeded.



	 *



	 * @param  evt object containing the results of the parse()



	 */



	public void parseCompleted(LogicExprParser.ParseEvent evt) {



		parseEvent = evt;



		if (evt.getResult())



			redrawForNewVariableCount(evt.getVariableCount());



		else



			trace.out("ti", "Parse of \"" + evt.getInput() +



					  "\" failed:\n" + evt.getErrorMsg());



	}







	/**



	 * Redraw the display to suit the given number of Boolean



	 * variables in the student expression.



	 *



	 * @param  nVars number of variables



	 * @deprecated use {@link #redrawForNewVariableCount(int)} instead



	 */



	private void _old_redrawForNewVariableCount(int nVars) {



		trace.out("ti", "TruthTable.redrawForNewVariableCount(): nVars=" +



				  nVars);



		switch(nVars) {



		case 1:



			commTable1.setRows(2);



			commTextField14.setVisible(true);



			one_var.setVisible(true);



			commTextField9.setVisible(false);



			two_var.setVisible(false);



			commTextField15.setVisible(false);



			three_var.setVisible(false);



			commTextField16.setVisible(false);



			four_var.setVisible(false);



			break;







		case 2:



			commTable1.setRows(4);



			commTextField14.setVisible(true);



			one_var.setVisible(true);



			commTextField9.setVisible(true);



			two_var.setVisible(true);



			commTextField15.setVisible(false);



			three_var.setVisible(false);



			commTextField16.setVisible(false);



			four_var.setVisible(false);



			break;







		case 3:



			commTable1.setRows(8);



			commTextField14.setVisible(true);



			one_var.setVisible(true);



			commTextField9.setVisible(true);



			two_var.setVisible(true);



			commTextField15.setVisible(true);



			three_var.setVisible(true);



			commTextField16.setVisible(false);



			four_var.setVisible(false);



			break;







		case 4:



			commTable1.setRows(16);



			commTextField14.setVisible(true);



			one_var.setVisible(true);



			commTextField9.setVisible(true);



			two_var.setVisible(true);



			commTextField15.setVisible(true);



			three_var.setVisible(true);



			commTextField16.setVisible(true);



			four_var.setVisible(true);



			break;







		default:



			throw new IllegalArgumentException("Invalid number of variables: " +



											   nVars);



		}



		switchablePanel.setVisible(true);



	}



    



	/**



	 * Default widget setup for initial condition (no expression yet)



	 * and for degenerate case (no variables).



	 */



    private void initialSetup(){



		setSize(1085,820);



        this.dummyButton.setVisible(false);



        this.one_var.setVisible(false);



        this.two_var.setVisible(false);



        this.three_var.setVisible(false);



        this.four_var.setVisible(false);



        this.switchablePanel.add(chooseDonePanel);



        chooseDonePanel.setBounds(203, 15, 1060, 140);



        this.commTable1.setVisible(false);        



        this.jPanel1.setVisible(false);



        this.headerPanel.setVisible(false);



        this.jTextArea1.setVisible(false);



        this.Done.setVisible(false);



    }







   



	/**



	 * Redraw the display to suit the given number of Boolean



	 * variables in the student expression.



	 *



	 * @param  nVars number of variables



	 */



    private void redrawForNewVariableCount(int nVars) {



        this.switchablePanel.setVisible(true);



        this.jPanel1.setVisible(true);



        this.headerPanel.setVisible(true);



        this.jTextArea1.setVisible(true);



        this.commTable1.setVisible(true);



        this.Done.setVisible(true);



        



        switch (nVars) {



			case 0: {



				initialSetup();



				break;



			}



            case 1:   {



                this.dummyButton.setSelected(true);



                this.commTable1.setRows(2);  //sets the # of rows



                //change the 4th value here to set height of table



                //left-justify the truth table with this x value



                int newX=0-(40*Math.abs((nVars-4)));



                add(switchablePanel);



                switchablePanel.setBounds(newX, 10, 1090, 770);



                this.switchablePanel.add(commTable1);



                commTable1.setBounds(203, 108, 850, 64);



                //set the 2nd value here to set location of radio button line



                this.switchablePanel.add(chooseDonePanel);



                chooseDonePanel.setBounds(203, 175, 1060, 140);



                //turn proper TF values on and off



                this.one_var.setVisible(true);



                this.two_var.setVisible(false);



                this.three_var.setVisible(false);



                this.four_var.setVisible(false);



                //turn on or off proper variable widgets



                this.commTextField16.setVisible(false);



                this.commTextField15.setVisible(false);



                this.commTextField9.setVisible(false);



                



                this.setSize(1085, 350);



				break;



			}



            case 2:   {



                this.dummyButton.setSelected(true);



                this.commTable1.setRows(4);



                int newX=0-(40*Math.abs((nVars-4)));



                add(switchablePanel);



                switchablePanel.setBounds(newX, 10, 1090, 770);



                this.switchablePanel.add(commTable1);



                commTable1.setBounds(203, 108, 850, 132);



                this.switchablePanel.add(chooseDonePanel);



                chooseDonePanel.setBounds(203, 240, 1060, 140);



                this.two_var.setVisible(true);



                this.one_var.setVisible(false);



                this.three_var.setVisible(false);



                this.four_var.setVisible(false);



                this.commTextField16.setVisible(false);



                this.commTextField15.setVisible(false);



                this.commTextField9.setVisible(true);



                this.setSize(1085, 410);



				break;



			}



            case 3:   {



                this.dummyButton.setSelected(true);                



                this.commTable1.setRows(8);  //sets the # of rows



                //change the 4th value here to set height of table



                //left-justify the truth table with this x value



                int newX=0-(40*Math.abs((nVars-4)));



                add(switchablePanel);



                switchablePanel.setBounds(newX, 10, 1090, 770);



                this.switchablePanel.add(commTable1);



                commTable1.setBounds(203, 108, 850, 265);



                //set the 2nd value here to set location of radio button line



                this.switchablePanel.add(chooseDonePanel);



                chooseDonePanel.setBounds(203, 375, 1060, 140);



                //turn proper TF values on and off



                this.three_var.setVisible(true);



                this.two_var.setVisible(false);



                this.one_var.setVisible(false);



                this.four_var.setVisible(false);



                //turn on or off proper variable widgets



                this.commTextField16.setVisible(false);



                this.commTextField15.setVisible(true);



                this.commTextField9.setVisible(true);



                



                this.setSize(1085, 560);



				break;



			}



            case 4:  {



                this.dummyButton.setSelected(true);                



                this.commTable1.setRows(16);  //sets the # of rows



                //change the 4th value here to set height of table



                //left-justify the truth table with this x value



                int newX=0-(40*Math.abs((nVars-4)));



                add(switchablePanel);



                switchablePanel.setBounds(newX, 10, 1090, 770);



                this.switchablePanel.add(commTable1);



                commTable1.setBounds(203, 108, 850, 530);



                //set the 2nd value here to set location of radio button line



                this.switchablePanel.add(chooseDonePanel);



                chooseDonePanel.setBounds(203, 635, 1060, 140);



                //turn proper TF values on and off



                this.four_var.setVisible(true);



                this.two_var.setVisible(false);



                this.three_var.setVisible(false);



                this.one_var.setVisible(false);



                //turn on or off proper variable widgets



                this.commTextField16.setVisible(true);



                this.commTextField15.setVisible(true);



                this.commTextField9.setVisible(true);



                



                this.setSize(1085,820);



				break;



			}



			default: {



				throw new IllegalArgumentException("Invalid number of" +



												   " variables: " + nVars);



			}



        } // end switch()



    }







	public BR_Controller getController() {
		// TODO Auto-generated method stub
		return controller;
	}







	public void setController(BR_Controller controller) {
		 
		this.controller = controller;
	}



}



