/*
 * Created on Mar 9, 2005
 *
 */
package edu.cmu.pact.BehaviorRecorder.ProblemModel.Graph;

import java.io.Serializable;
import java.util.Vector;

import org.jdom.Element;

import edu.cmu.pact.BehaviorRecorder.Controller.ActionLabelHandler;
import edu.cmu.pact.BehaviorRecorder.Controller.BR_Controller;
import edu.cmu.pact.BehaviorRecorder.Controller.LinkEditFunctions;
import edu.cmu.pact.BehaviorRecorder.Controller.RuleLabelHandler;
import edu.cmu.pact.BehaviorRecorder.ProblemModel.ProblemStateWriter;
import edu.cmu.pact.BehaviorRecorder.View.ActionLabel;
import edu.cmu.pact.BehaviorRecorder.View.CheckLispLabel;
import edu.cmu.pact.BehaviorRecorder.View.RuleLabel;
import edu.cmu.pact.BehaviorRecorder.jgraphwindow.BR_JGraphEdge;
import edu.cmu.pact.Utilities.Utils;
import edu.cmu.pact.miss.Sai;

public class ProblemEdge implements Serializable {

	private static final long serialVersionUID = -4402015128879088164L;

	/** Tag name for element generated by {@link #toElement()}. */
    public static final String ELEMENT_NAME = "edge";

	// Each ESDiEdge object is a directed graph edge, and optionally
    // contains an attribute.
    public static final int SOURCE = 0, DEST = 1;

    EdgeData edgeData;

    LinkEditFunctions functions;
    
    public ProblemNode source, dest;

    /** Retreive the source or "Parent" node of the edge. */
    public ProblemNode getSource() { return this.source; }

    /** Retreive the destination or "Child" node of the edge. */
    public ProblemNode getDest() { return this.dest; }

    ProblemEdge nextEdge;
    ProblemEdge prevEdge;

    private BR_JGraphEdge jgraphEdge;

    /**
     * Enable a calling routine to set transient fields after deserializing.
     * @param controller value for {@link #controller}
     */
    public void restoreTransients(BR_Controller controller) {
    	if (edgeData != null)
    		edgeData.restoreTransients(controller);
    	if (functions != null)
    		functions.restoreTransients(controller);
    	if (jgraphEdge != null)
    		jgraphEdge.restoreTransients(controller);
    }

    //////////// Constructor ////////////

    public ProblemEdge() {}
    
    public ProblemEdge(ProblemNode source, ProblemNode dest, EdgeData attr) {
        this.source = source;
        this.dest = dest;
        this.edgeData = attr;
        this.prevEdge = null;
        this.nextEdge = null;
        if(!Utils.isRuntime())
        	this.functions = new LinkEditFunctions(this, attr.getController());
    }

    public String toString() {
        return "ProblemEdge: [" + source + ", " + dest + "]";
    }

    /**
     * @return multi-line, indented format of {@link #toElement()}
     */
    public String toXMLString() {
    	return ProblemStateWriter.multiLineOutputter.outputString(toElement());   	
    }
    
    /**
     * Convert to XML element suitable for brd file.
     * @return <edge> element
     */
	public Element toElement() {
		Element elt = new Element(ELEMENT_NAME);
		Element child = null;
		if ((child = edgeData.getActionLabelElement()) != null)
			elt.addContent(child);
		if ((child = edgeData.getPreLispCheckLabel().toElement()) != null)
			elt.addContent(child);
		for (RuleLabel rl : edgeData.getRuleLabels())
			elt.addContent(rl.toElement());
		
		
		ProblemNode node = getNodes()[ProblemEdge.SOURCE];
		if(node != null)
			elt.addContent(new Element("sourceID").setText(Integer.toString(node.getUniqueID())));
		node = getNodes()[ProblemEdge.DEST];
		if(node != null)
			elt.addContent(new Element("destID").setText(Integer.toString(node.getUniqueID())));
		
		elt.addContent(new Element("traversalCount").setText(Integer.toString(edgeData.getTraversalCount())));
		elt.addContent(new Element("SimSt"));   // FIXME temp until SimSt implementation done
		
		Vector assocElements = edgeData.getAssociatedElements();
		Vector assocElementsValues = edgeData.getAssociatedElementsValues();
		for (int i = 0; i < assocElements.size(); ++i) {
			Element assocElt = new Element("element");
			String name, value;
			if ((name = assocElements.get(i).toString()) != null)
				assocElt.setAttribute("name", name);
			if ((value = assocElementsValues.get(i).toString()) != null)
				assocElt.setAttribute("value", value);
			elt.addContent(assocElt);
		}
		
		return elt;
	}

    public BR_Controller getController() {
        return edgeData.getController();
    }
    
    // Return an array containing the two nodes connected by this edge.
    // (If the graph is directed, the array will contain the edge's source
    // and destination, in that order.)
    public ProblemNode[] getNodes() {
        return new ProblemNode[] { this.source, this.dest };
    }

    // Return the attribute contained in this edge, or null if there is
    // none.
    public EdgeData getEdgeData() {
        return this.edgeData;
    }
    
    // Change the attribute contained in this edge to attr.
    public void setEdgeData(EdgeData attr) {
        this.edgeData = attr;
    }

    public LinkEditFunctions getLinkEditFunctions(){
    	return functions;
    }
    
    
    public String getActionType() {
        return edgeData.getActionType();
    }
    
    public String getInput() {
        return (String)edgeData.getInput().get(0);
    }
    
    public String getSelection() {
        return (String)edgeData.getSelection().get(0);
    }
    
    public String getAction() {
        return (String)edgeData.getAction().get(0);
    }
    
    public boolean isPreferredEdge() {

        return edgeData.isPreferredEdge();
    }
    
    public Vector /* String */ getSkills() {
    	if(edgeData == null)
    		return new Vector();
        return edgeData.getSkills();
    }

    public boolean isBuggy() {
        String authorintent = edgeData.getActionType();
        return (authorintent.equalsIgnoreCase(EdgeData.BUGGY_ACTION) 
                || authorintent.equalsIgnoreCase(EdgeData.UNTRACEABLE_ERROR));
    }

    public boolean hasBuggyMessage () {
        String buggyMsg = edgeData.getBuggyMsg();
        return (!buggyMsg.equals(""));
    }

    public boolean isGiven() {
        String edgeActionType = edgeData.getActionType();
        return (edgeActionType.equalsIgnoreCase(EdgeData.GIVEN_ACTION));
    }
    
    public boolean minGreaterThanMaxTraversals(){
    	return (edgeData.getMinTraversals()>edgeData.getMaxTraversals());
    }

    public boolean isSkip() {
        String edgeActionType = edgeData.getActionType();
        return (edgeActionType.equalsIgnoreCase(EdgeData.SKIP_ACTION));
    }

    
    public boolean isCorrect() {
        String actionType = edgeData.getActionType();
        return (actionType.equalsIgnoreCase(EdgeData.CORRECT_ACTION));
    }

    //29Sep2006 -Gustavo
    //We are adding this method because we are interested in running the learning only on
    //"untraceable actions"	
    public boolean isCltErrorAction() {
        String actionType = edgeData.getActionType();
        return (actionType.equalsIgnoreCase(EdgeData.CLT_ERROR_ACTION));
    }

    public boolean isDone() {

        Vector selection = edgeData.getSelection();

        String tempSelectionString;

        for (int i = 0; i < selection.size(); i++) {
            tempSelectionString = (String) selection.elementAt(i);
            if (tempSelectionString.equalsIgnoreCase("Done"))
                return true;
        }

        return false;
    }

    /**
     * test whether the Edge's author intent is CORRECT_ACTION or
     * FIREABLE_BUGGY_ACTION.
     */
    // ///////////////////////////////////////////////////////////////////////////////////////////////

    public boolean isCorrectorFireableBuggy() {

        String actionType = edgeData.getActionType();

        if (actionType.equalsIgnoreCase(EdgeData.CORRECT_ACTION)
                || actionType.equalsIgnoreCase(EdgeData.FIREABLE_BUGGY_ACTION))
            return true;

        return false;
    }

    public boolean selectionNameMatch(String widgetSelectionName) {
        if (widgetSelectionName == null)
            return false;

        if (widgetSelectionName.trim().length() == 0)
            return false;

        Vector selection = edgeData.getSelection();
        String firstSelection = (String) selection.elementAt(0);

        if (widgetSelectionName.equalsIgnoreCase(firstSelection))
            return true;

        return false;
    }

    public boolean hasDialogueName() {
        String dialogueName = edgeData.getDialogueName().trim();

        if (dialogueName.length() != 0)
            return true;

        return false;
    }

    public String getDialogueName() {
        String dialogueName = edgeData.getDialogueName().trim();

        return dialogueName;
    }

    public boolean hasHints() {
        Vector hints = edgeData.getHints();

        if (hints.size() > 0)
            return true;

        return false;
    }

    public ActionLabelHandler getActionHandler() {
        return edgeData.getActionLabel().getHandler();
    }

    public ActionLabel getActionLabel() {
        return edgeData.getActionLabel();
    }

    public CheckLispLabel getPreLispCheckLabel() {
        return edgeData.getPreLispCheckLabel();
    }

    public void setJGraphEdge(BR_JGraphEdge edge) {
        this.jgraphEdge = edge;
    }

    public BR_JGraphEdge getJGraphEdge() {
        return this.jgraphEdge;
    }
    
    public Sai getSai(){       
        Sai sai = new Sai(edgeData.getSelection(), edgeData.getAction(), edgeData.getInput());
        return sai;
    }

    public int getUniqueID() {
        return getEdgeData().getUniqueID();
    }
    
    public void addEdgeLabels() {
        EdgeData myEdge = getEdgeData();

        myEdge.getActionLabel().addHandler(
                new ActionLabelHandler(myEdge.getActionLabel(), getController()));

        // add ruleLabels
        int rulesNumber = myEdge.getRuleLabels().size();
        RuleLabel tempRuleLabel;
        for (int i = 0; i < rulesNumber; i++) {
            tempRuleLabel = (RuleLabel) myEdge.getRuleLabels().elementAt(i);
            tempRuleLabel.addMouseListener(new RuleLabelHandler(tempRuleLabel,
                    this, getController()));
        }

        setEdgeLabels(this);
    }
    
    public void setEdgeLabels(ProblemEdge Edge) {
    	EdgeData myedge;
    	myedge = Edge.getEdgeData();
    	myedge.updateMovedFromEdgeView();
    }
    
    //////////////////////////////////////////////////////////////////////////////////////////////
}