/*
 * TutorTemplate.java
 *
 * Created on May 27, 2004, 10:27 PM
 */

package edu.cmu.pact.jess.matchers;

import javax.swing.JPanel;

import pact.CommWidgets.event.StudentActionEvent;
import pact.CommWidgets.event.StudentActionListener;
import edu.cmu.pact.BehaviorRecorder.Controller.SingleSessionLauncher;
import edu.cmu.pact.Utilities.trace;

/**
 *
 * @author  sanket
 */
public class TutorInterface extends JPanel {
    
    /** Creates new form TutorInterface */
    public TutorInterface() {
        super();
        
        initComponents();
        
        table1.addStudentActionListener(new StudentActionListener() {
        	public void studentActionPerformed(StudentActionEvent sae) {
        		trace.out("br", "sae received "+sae);
        	}
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
    	
        table1 = new pact.CommWidgets.JCommTable() {
        	public void doCorrectAction(String selection, String input) {
        		super.doCorrectAction(selection, input);
        		trace.out("FOUND IT");
        	}
        };
        jLabel1 = new javax.swing.JLabel();
        tf1 = new pact.CommWidgets.JCommTextField();
        tf2 = new pact.CommWidgets.JCommTextField();

        setLayout(null);

        table1.setColumns(6);
        table1.setCommName("table1");
        add(table1);
        table1.setBounds(50, 30, 230, 140);

        tf1.setCommName("tf1");
        add(tf1);
        tf1.setBounds(50, 180, 140, 20);

        tf2.setCommName("tf2");
        add(tf2);
        tf2.setBounds(50, 210, 140, 20);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 24));
        jLabel1.setText("+");
        add(jLabel1);
        jLabel1.setBounds(30, 100, 20, 30);

    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new SingleSessionLauncher(args).launch(new TutorInterface());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private pact.CommWidgets.JCommTextField tf1;
    private pact.CommWidgets.JCommTextField tf2;
    private pact.CommWidgets.JCommTable table1;
    // End of variables declaration//GEN-END:variables
    
}
