/*
 * TutorTemplate.java
 *
 * Created on May 27, 2004, 10:27 PM
 */

package edu.cmu.pact.miss.EquationTutor;

import javax.swing.JPanel;

import edu.cmu.pact.BehaviorRecorder.Controller.SingleSessionLauncher;
import edu.cmu.pact.Utilities.trace;

/**
 *
 * @author  sanket
 */
public class EquationTutor extends JPanel {

    /** Creates new form EquationTutor */
    public EquationTutor() {
        super();
        
        initComponents();
        setSize(300, 320);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        commLabel1 = new pact.CommWidgets.JCommLabel();
        commLabel2 = new pact.CommWidgets.JCommLabel();
        commLabel3 = new pact.CommWidgets.JCommLabel();
        commLabel4 = new pact.CommWidgets.JCommLabel();
        commLabel5 = new pact.CommWidgets.JCommLabel();
        commLabel6 = new pact.CommWidgets.JCommLabel();
        commLabel7 = new pact.CommWidgets.JCommLabel();
        commLabel8 = new pact.CommWidgets.JCommLabel();
        commTable1 = new pact.CommWidgets.JCommTable();
        commTable2 = new pact.CommWidgets.JCommTable();

        setLayout(null);

        commLabel1.setFont(new java.awt.Font("Dialog", 0, 36));
        commLabel1.setText("=");
		commLabel1.setCommName("commLabel1");
        add(commLabel1);
        commLabel1.setBounds(230, 370, 30, 30);

        commLabel2.setFont(new java.awt.Font("Dialog", 0, 36));
        commLabel2.setText("=");
		commLabel2.setCommName("commLabel2");
        add(commLabel2);
        commLabel2.setBounds(230, 40, 30, 30);

        commLabel3.setFont(new java.awt.Font("Dialog", 0, 36));
        commLabel3.setText("=");
		commLabel3.setCommName("commLabel3");
        add(commLabel3);
        commLabel3.setBounds(230, 90, 30, 30);

        commLabel4.setFont(new java.awt.Font("Dialog", 0, 36));
        commLabel4.setText("=");
		commLabel4.setCommName("commLabel4");
        add(commLabel4);
        commLabel4.setBounds(230, 140, 30, 30);

        commLabel5.setFont(new java.awt.Font("Dialog", 0, 36));
        commLabel5.setText("=");
		commLabel5.setCommName("commLabel5");
        add(commLabel5);
        commLabel5.setBounds(230, 180, 30, 30);

        commLabel6.setFont(new java.awt.Font("Dialog", 0, 36));
        commLabel6.setText("=");
		commLabel6.setCommName("commLabel6");
        add(commLabel6);
        commLabel6.setBounds(230, 230, 30, 30);

        commLabel7.setFont(new java.awt.Font("Dialog", 0, 36));
        commLabel7.setText("=");
		commLabel7.setCommName("commLabel7");
        add(commLabel7);
        commLabel7.setBounds(230, 280, 30, 30);

        commLabel8.setFont(new java.awt.Font("Dialog", 0, 36));
        commLabel8.setText("=");
		commLabel8.setCommName("commLabel8");
        add(commLabel8);
        commLabel8.setBounds(230, 320, 30, 30);

        commTable1.setFont(new java.awt.Font("Dialog", 0, 36));
        commTable1.setColumns(1);
        commTable1.setRows(8);
		commTable1.setCommName("commTable1");
        add(commTable1);
        commTable1.setBounds(260, 30, 200, 380);

        commTable2.setFont(new java.awt.Font("Dialog", 0, 36));
        commTable2.setColumns(1);
        commTable2.setRows(8);
		commTable2.setCommName("commTable2");
        add(commTable2);
        commTable2.setBounds(34, 30, 190, 380);

    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

	for (int i = 0; i < args.length; i++) {
	    trace.out("args[" + i + "] = " + args[i]);
	}

	SingleSessionLauncher tutor = new SingleSessionLauncher( args );
	tutor.launch(new EquationTutor());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pact.CommWidgets.JCommLabel commLabel1;
    private pact.CommWidgets.JCommLabel commLabel2;
    private pact.CommWidgets.JCommLabel commLabel3;
    private pact.CommWidgets.JCommLabel commLabel4;
    private pact.CommWidgets.JCommLabel commLabel5;
    private pact.CommWidgets.JCommLabel commLabel6;
    private pact.CommWidgets.JCommLabel commLabel7;
    private pact.CommWidgets.JCommLabel commLabel8;
    private pact.CommWidgets.JCommTable commTable1;
    private pact.CommWidgets.JCommTable commTable2;
    // End of variables declaration//GEN-END:variables
    
}
