/*
 * TutorTemplate.java
 *
 * Created on May 27, 2004, 10:27 PM
 */

package SimStEquation;

import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.UIManager;
import javax.swing.JPanel;
import java.awt.*;
import java.lang.reflect.Field;

import edu.cmu.pact.Utilities.trace;
import pact.DorminWidgets.*;
//import edu.wpi.trg.assistments.jess.logActions.*;
import edu.cmu.pact.BehaviorRecorder.Controller.*;

/**
 *
 * @author  sanket
 */
public class EquationTutor extends JPanel {

    /** Creates new form EquationTutor */
    public EquationTutor() {
        super();
        
        initComponents();
        setSize(300, 320);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        dorminLabel1 = new pact.DorminWidgets.DorminLabel();
        dorminLabel2 = new pact.DorminWidgets.DorminLabel();
        dorminLabel3 = new pact.DorminWidgets.DorminLabel();
        dorminLabel4 = new pact.DorminWidgets.DorminLabel();
        dorminLabel5 = new pact.DorminWidgets.DorminLabel();
        dorminLabel6 = new pact.DorminWidgets.DorminLabel();
        dorminLabel7 = new pact.DorminWidgets.DorminLabel();
        dorminLabel8 = new pact.DorminWidgets.DorminLabel();
        dorminTable1 = new pact.DorminWidgets.DorminTable();
        dorminTable2 = new pact.DorminWidgets.DorminTable();

        setLayout(null);

        dorminLabel1.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminLabel1.setText("=");
        add(dorminLabel1);
        dorminLabel1.setBounds(230, 370, 30, 30);

        dorminLabel2.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminLabel2.setText("=");
        add(dorminLabel2);
        dorminLabel2.setBounds(230, 40, 30, 30);

        dorminLabel3.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminLabel3.setText("=");
        add(dorminLabel3);
        dorminLabel3.setBounds(230, 90, 30, 30);

        dorminLabel4.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminLabel4.setText("=");
        add(dorminLabel4);
        dorminLabel4.setBounds(230, 140, 30, 30);

        dorminLabel5.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminLabel5.setText("=");
        add(dorminLabel5);
        dorminLabel5.setBounds(230, 180, 30, 30);

        dorminLabel6.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminLabel6.setText("=");
        add(dorminLabel6);
        dorminLabel6.setBounds(230, 230, 30, 30);

        dorminLabel7.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminLabel7.setText("=");
        add(dorminLabel7);
        dorminLabel7.setBounds(230, 280, 30, 30);

        dorminLabel8.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminLabel8.setText("=");
        add(dorminLabel8);
        dorminLabel8.setBounds(230, 320, 30, 30);

        dorminTable1.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminTable1.setColumns(1);
        dorminTable1.setRows(8);
        add(dorminTable1);
        dorminTable1.setBounds(260, 30, 200, 380);

        dorminTable2.setFont(new java.awt.Font("Dialog", 0, 36));
        dorminTable2.setColumns(1);
        dorminTable2.setRows(8);
        add(dorminTable2);
        dorminTable2.setBounds(34, 30, 190, 380);

    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

	for (int i = 0; i < args.length; i++) {
	    trace.out("args[" + i + "] = " + args[i]);
	}

	CTAT_Launcher tutor = new CTAT_Launcher( args );
	tutor.launch(new EquationTutor());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pact.DorminWidgets.DorminLabel dorminLabel1;
    private pact.DorminWidgets.DorminLabel dorminLabel2;
    private pact.DorminWidgets.DorminLabel dorminLabel3;
    private pact.DorminWidgets.DorminLabel dorminLabel4;
    private pact.DorminWidgets.DorminLabel dorminLabel5;
    private pact.DorminWidgets.DorminLabel dorminLabel6;
    private pact.DorminWidgets.DorminLabel dorminLabel7;
    private pact.DorminWidgets.DorminLabel dorminLabel8;
    private pact.DorminWidgets.DorminTable dorminTable1;
    private pact.DorminWidgets.DorminTable dorminTable2;
    // End of variables declaration//GEN-END:variables
    
}
