package edu.cmu.pact.Utilities;

/**
 * Version number and build date for null.
 * THIS CODE IS GENERATED by VersionInfoGenerator.
 */
public class VersionInformation {
    public static String RELEASE_NAME = "CTAT 3.4.0i";
    public static String VERSION_NUMBER = "20210419-1600";
    public static String BUILD_DATE = "19 April 2021";

    private static VersionInfoGenerator.LicenseType licenseType = VersionInfoGenerator.LicenseType.internal;

    public static String getReleaseString() {
        return RELEASE_NAME+", "+VERSION_NUMBER+", "+BUILD_DATE;
    }

    public static void main(String[] args) {
        System.out.println(getReleaseString());
    }

    /**
     * @return true if the Carnegie Learning libraries are available; else false
     */
    public static boolean includesCL() { return licenseType == VersionInfoGenerator.LicenseType.internal; }

    /**
     * @return true if Simulated Student mode is available; else false
     */
    public static boolean includesSimSt() { return licenseType == VersionInfoGenerator.LicenseType.internal; }

    /** Result of last {@link #includesJess()} call. */
    private static Boolean lastJessResult = null;

    /**
     * @return true if can instantiate the {@link jess.Rete} class; else false
     */
    public static boolean includesJess() {
        if(lastJessResult != null)
            return lastJessResult.booleanValue();
        boolean result;
        try {
            Class cls = Class.forName("jess.Rete");
            result = (cls.newInstance() != null);
        } catch (NoClassDefFoundError ncdfe) {
            result = false;
        } catch (ClassNotFoundException cnfe) {
            result = false;
        } catch (Throwable t) {
            result = (licenseType != VersionInfoGenerator.LicenseType.commercial);
        }
        lastJessResult = new Boolean(result);
        return result;
    }


    /** True if we are actually running Sim Student. */
    private static boolean runningSimSt = false;

    /**
     * @return true if actually running Sim Student
     */
    public static boolean isRunningSimSt() {
        return runningSimSt && includesSimSt();
    }

    /**
     * @param new value for {@link #runningSimSt}
     */
    public static void setRunningSimSt(boolean b) {
        runningSimSt = b;
    }


    /**
     * @return URL of web page having the license agreement or null
     */
    public static String getWebPage() {
        return "http://ctat.pact.cs.cmu.edu/license";
    }

    /**
     * @return menu item labeled "CTAT License" or null
     */
    public static javax.swing.JMenuItem getMenuItem() {
        return new javax.swing.JMenuItem("CTAT License");
    }

    /**
     * @return HTML string telling the location of the license file or empty string
     */
    public static String getFileReferenceString() {
        return "License: "+VersionInformation.currentDir()+"CTAT academic license.html.<br><br>";
    }

    /**
     * @return current directory from System property user.dir or empty string.
     */
    private static String currentDir() {
        String result = System.getProperty("user.dir");
        if (result == null || result.length() < 1)
            return "";
        return result+java.io.File.separator;
    }

}
