// Kevin Jeffries, May 2013

package edu.cmu.pact.ctat;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;

import edu.cmu.hcii.ctat.CTATHTTPExchange;
import edu.cmu.pact.BehaviorRecorder.Controller.BR_Controller;
import edu.cmu.pact.SocketProxy.HTTPToolProxy;
import edu.cmu.pact.SocketProxy.SocketProxy;
import edu.cmu.pact.TutoringService.LauncherHandler;
import edu.cmu.pact.Utilities.trace;

/**
 * A MessageObject that is created from and associated with an HTTP request. The HTTP exchange object that
 * was parsed to create the MessageObject is remembered so it can be used to send the response to the message.
 * 
 * @author Kevin Jeffries
 *
 */
public class HTTPMessageObject extends MessageObject {
	
	/** Contains the request instance and response stream. */
	private HTTPToolProxy httpToolProxy;
	
	/**
	 * @return the {@link #httpToolProxy}
	 */
	public HTTPToolProxy getHttpToolProxy() {
		return httpToolProxy;
	}

	/** Encoding for {@link #messageFromExchange(CTATHTTPExchange)}. */
	private static final String encoding = "UTF-8";

	/**
	 * Creates {@link #httpToolProxy} to hold the output path for the response.
	 * @param exchange
	 * @param format
	 * @param controller
	 */
	public HTTPMessageObject(CTATHTTPExchange exchange, int format, BR_Controller controller) {
		super(messageFromExchange(exchange, format));
		this.httpToolProxy = new HTTPToolProxy(exchange, format, controller);
	}

	/**
	 * @return {@link #httpToolProxy}.{@link HTTPToolProxy#getHttpExchange()}
	 */
	public CTATHTTPExchange getHttpExchange() {
		return httpToolProxy.getHttpExchange();
	}
	
	/**
	 * Pulls in the body of the request on the given HTTP-exchange and parses it into a MessageObject
	 * 
	 * @param exchange HTTP exchange whose request body is the XML for a message
	 * @return a MesssageObject generated by calling MessageObject.parse on the string in the HTTP request
	 */
	public static MessageObject messageFromExchange(CTATHTTPExchange exchange, int msgFmt) {
		String str = "";
		try {
			str = exchange.getRequestBodyAsString();
		} catch (IOException e) {
			throw new RuntimeException("I/O exception while reading HTTP message");
		}
		if (trace.getDebugCode("tsltsp"))
			trace.outNT("tsltsp", exchange.getRequestHeaderConcatenated(LauncherHandler.CTATSESSION_HEADER)+" "+str);
		MessageObject mo = SocketProxy.convertMsg(str, msgFmt);
		return mo;
	}
}
