/*
 * TutorTemplate.java
 *
 * Created on May 27, 2004, 10:27 PM
 */

package pact.CommWidgets;

import javax.swing.JPanel;

import edu.cmu.pact.BehaviorRecorder.Controller.SingleSessionLauncher;

/**
 *
 * @author  sanket
 */
public class TutorInterfaceZ extends JPanel {
    
    /** Creates new form TutorTemplate */
    public TutorInterfaceZ() {
        super();
        
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        commMultipleChoice1 = new pact.CommWidgets.JCommMultipleChoice();
        commComposer1 = new pact.CommWidgets.JCommComposer();

        setLayout(null);

        commMultipleChoice1.setChoiceTextFont(new java.awt.Font("Arial", 0, 12));
        commMultipleChoice1.setQuestionFont(new java.awt.Font("", 1, 12));
		commMultipleChoice1.setCommName("commMultipleChoice1");
        add(commMultipleChoice1);
        commMultipleChoice1.setBounds(50, 50, 120, 140);

        commComposer1.setComboBoxesNumber(10);
        commComposer1.setComboBoxesWidths("50, 70, 100");
        commComposer1.setItemValues("ssss, ttttt;\n ;\nqqqqqq, ppppp;\naaaa, bbbb;;\n");
        commComposer1.setValue1("");
        commComposer1.setValue2("");
        commComposer1.setValue3("");
        commComposer1.setValue4("");
		commComposer1.setCommName("commComposer1");
        add(commComposer1);
        commComposer1.setBounds(10, 240, 480, 180);

    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new SingleSessionLauncher().launch(new TutorInterfaceZ());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pact.CommWidgets.JCommComposer commComposer1;
    private pact.CommWidgets.JCommMultipleChoice commMultipleChoice1;
    // End of variables declaration//GEN-END:variables
    
}
