/* Generated By:JavaCC: Do not edit this line. SM.java */
package edu.cmu.old_pact.cmu.sm;

public class SM implements SMConstants {
    static java.util.Stack argStack = new java.util.Stack();
        static SMTokenManager tokes = null;
        static SM parser = null;

    /*the default is to treat any character as a variable*/
    static String[] default_vars = {"a","b","c","d","e","f","g","h","i","j","k","l","m",
                                    "n","o","p","q","r","s","t","u","v","w","x","y","z",
                                    "A","B","C","D","E","F","G","H","I","J","K","L","M",
                                    "N","O","P","Q","R","S","T","U","V","W","X","Y","Z"};
    static String[] vars;

    public static VariableExpression makeLitOrVarExpr(String v){
        for(int i=0;i<vars.length;i++){
            if(vars[i].equalsIgnoreCase(v)){
                return new VariableExpression(v);
            }
        }

        return new LiteralExpression(v);
    }

    public static Expression readExpression(String[] variables) throws ParseException{
        vars = variables;
        return readExpr();
    }

    public static Expression readExpression() throws ParseException{
        vars = default_vars;
        return readExpr();
    }

    public static void testParse(String expr_base) {
        testParse(expr_base,new String[0]);
    }

        /*'same' is a string representation of the expression that is also
	  acceptable as output from the parser*/
        public static void testParse(String expr_base,String same){
                testParse(expr_base,new String[] {same});
        }

    /*'same' is an array of string representations of the expression
      that are also acceptable as output from the parser.  see below
      for some examples of how this can be useful.*/
    public static void testParse(String expr_base,String[] same) {
        String expr = new String(expr_base + "\n");

        ASCII_CharStream instream = new ASCII_CharStream(new java.io.StringBufferInputStream(expr),0,0,expr.length());

                if (tokes == null) {
                        tokes = new SMTokenManager(instream);
                        parser = new SM(tokes);
                }
                else {
                SMTokenManager.ReInit(instream); //re-initialize token manager (get reused each time)
                        parser.ReInit(tokes);
                }

        try {
                Expression parseValue = SM.readExpression();
                if (parseValue == null)
                        System.out.println("testParse: Expression "+expr_base+" does not parse");
                else {
                        String outString = parseValue.toString();
                                String errorCode = "[  * ERROR *   ]";
                                for(int i=0;i<same.length;i++){
                                        if(outString.equals(same[i])){
                                                errorCode = "[     okay     ]";
                                        }
                                }
                                if(outString.equals(expr_base)){
                                        if(same.length > 0){
                                                errorCode = "[didn't convert]";
                                        }
                                        else{
                                                errorCode = "[  identical   ]";
                                        }
                                }
                                if(!errorCode.equals("[  identical   ]")){
                                        System.out.println("testParse: " + errorCode + ": " + expr_base+" :: "+outString);
                                }
                                else{
                                        System.out.println("testParse: " + errorCode + ": " + expr_base);
                                }
                }
        } catch (ParseException x) {
                System.out.println("Parse error parsing "+expr_base+": " + x.toString());
        }
    }

        public static void testParser(){
                TestSM.testParser();
        }

/*readExpression -- the main function*/
  static final public Expression readExpr() throws ParseException {
    oe();
    jj_consume_token(EOL);
                {if (true) return ((Expression)(argStack.pop())).removeImpliedFences().removeRedundantFences();}
    throw new Error("Missing return statement in function");
  }

  static final public void oe() throws ParseException {
        Expression first;
        Expression second;
        Token op;
    expr();
    label_1:
    while (true) {
      if (jj_2_1(50)) {
        ;
      } else {
        break label_1;
      }
      oeOp();
      expr();
                second = (Expression)(argStack.pop());
                op = (Token)(argStack.pop());
                first = (Expression)(argStack.pop());
                if (op.kind == PLUS)
                        argStack.push(first.add(second));
                else
                        argStack.push(first.subtract(second));
                if(Debug.getDebugging()){
                        Debug.println("oe = expr (oeOp expr)+ :: "+(argStack.peek().toString()));
                }
    }
  }

  static final public void expr() throws ParseException {
        Expression first;
        Expression second;
        Token op;
    termOrCoeff();
    label_2:
    while (true) {
      if (jj_2_2(50)) {
        ;
      } else {
        break label_2;
      }
      mdOp();
      termOrCoeff();
                second = (Expression)(argStack.pop());
                op = (Token)(argStack.pop());
                first = (Expression)(argStack.pop());
                if (op.kind == MULTIPLY)
                        argStack.push(first.multiply(second));
                else
                        argStack.push(first.divide(second));
                if(Debug.getDebugging()){
                        Debug.println("expr = termOrCoeff (mdOp termOrCoeff)+ (term)+ :: "+(argStack.peek().toString()));
                }
    }
    label_3:
    while (true) {
      if (jj_2_3(50)) {
        ;
      } else {
        break label_3;
      }
      term();
                        second = (Expression)(argStack.pop());
                        first = (Expression)(argStack.pop());
                        argStack.push(first.multiply(second));
    }
  }

  static final public void termOrCoeff() throws ParseException {
    if (jj_2_5(50)) {
      term();
      label_4:
      while (true) {
        if (jj_2_4(50)) {
          ;
        } else {
          break label_4;
        }
        term();
                Expression second = (Expression)(argStack.pop());
                Expression first = (Expression)(argStack.pop());
                argStack.push(first.multiply(second));
                                if(Debug.getDebugging()){
                                        Debug.println("termOrCoeff = term term* :: "+argStack.peek().toString());
                                }
      }
    } else if (jj_2_6(50)) {
      coeffTerm();
                if(Debug.getDebugging()){
                        Debug.println("termOrCoeff = coeffTerm");
                }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//a coeffTerm is a coefficient (or negative sign) plus a term
//The defining characteristic of a coeffTerm is that (unlike a term), you can't
//just stick a number in front of it to get multiplication
  static final public void coeffTerm() throws ParseException {
        Expression term;
        Expression coefficient;
        Expression first;
        Expression second;
        Token op;
    if (jj_2_9(50)) {
      jj_consume_token(MINUS);
      termOrCoeff();
                term = (Expression)(argStack.pop());
                /*old way is bad because it removes double-negatives*/
                //argStack.push(term.negate());
                argStack.push(term.softNegate());
                if(Debug.getDebugging()){
                        Debug.println("coeffTerm = - term :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_10(50)) {
      jj_consume_token(PLUS);
      termOrCoeff();
                /*term = (Expression)(argStack.pop());
		  argStack.push(term);*/
                if(Debug.getDebugging()){
                        Debug.println("coeffTerm = + term :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_11(50)) {
      number();
      if (jj_2_7(50)) {
        mdOp();
        term();
                term = (Expression)(argStack.pop());
                op = (Token)(argStack.pop());
                coefficient = (Expression)(argStack.pop());
                if (op.kind == MULTIPLY)
                        argStack.push(coefficient.multiply(term));
                else
                        argStack.push(coefficient.divide(term));
                if(Debug.getDebugging()){
                        Debug.println("coeffTerm = number */ term :: "+(argStack.peek().toString()));
                }
      } else if (jj_2_8(50)) {
        term();
                term = (Expression)(argStack.pop());
                coefficient = (Expression)(argStack.pop());
                argStack.push(coefficient.multiply(term));
                if(Debug.getDebugging()){
                        Debug.println("coeffTerm = number term :: "+(argStack.peek().toString()));
                }
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void term() throws ParseException {
    if (jj_2_12(50)) {
      expon();
                if(Debug.getDebugging()){
                        Debug.println("term = expon :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_13(50)) {
      base();
                if(Debug.getDebugging()){
                        Debug.println("term = base :: "+(argStack.peek().toString()));
                }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//a base is something that can be raised to an exponent
  static final public void base() throws ParseException {
        Expression first;
        Token op;
        Expression second;
        NumberExpression exponent;
    if (jj_2_14(50)) {
      jj_consume_token(18);
      oe();
      jj_consume_token(19);
                first = (Expression)(argStack.pop());
                argStack.push(new FencedExpression(first));
                if(Debug.getDebugging()){
                        Debug.println("base = '(' oe ')' :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_15(50)) {
      jj_consume_token(20);
      oe();
      jj_consume_token(21);
                first = (Expression)(argStack.pop());
                argStack.push(new ImpliedFencedExpression(first));
                if(Debug.getDebugging()){
                        Debug.println("base = '[' oe ']' :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_16(50)) {
      variable();
                if(Debug.getDebugging()){
                        Debug.println("base = variable :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_17(50)) {
      number();
                if(Debug.getDebugging()){
                        Debug.println("base = number :: "+(argStack.peek().toString()));
                }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void expon() throws ParseException {
        Expression ex;
        NumberExpression exponent;
        Expression base;
    if (jj_2_25(50)) {
      base();
      label_5:
      while (true) {
        jj_consume_token(EXP);
        base();
                ex = (Expression)(argStack.pop());
                base = (Expression)(argStack.pop());
                argStack.push(base.power(ex));
                if(Debug.getDebugging()){
                        Debug.println("expon = base (^ base)+ :: "+(argStack.peek().toString()));
                }
        if (jj_2_18(50)) {
          ;
        } else {
          break label_5;
        }
      }
    } else if (jj_2_26(50)) {
      base();
      label_6:
      while (true) {
        jj_consume_token(EXP);
        jj_consume_token(MINUS);
        base();
                ex = (Expression)(argStack.pop());
                base = (Expression)(argStack.pop());
                /*old way is bad because it removes double-negatives*/
                //argStack.push(base.power(ex.negate()));
                argStack.push(base.power(ex.softNegate()));
                if(Debug.getDebugging()){
                        Debug.println("expon = base (^ <MINUS> base)+ :: "+(argStack.peek().toString()));
                }
        if (jj_2_19(50)) {
          ;
        } else {
          break label_6;
        }
      }
    } else if (jj_2_27(50)) {
      base();
      label_7:
      while (true) {
        jj_consume_token(EXP);
        jj_consume_token(PLUS);
        base();
                ex = (Expression)(argStack.pop());
                base = (Expression)(argStack.pop());
                argStack.push(base.power(ex));
                if(Debug.getDebugging()){
                        Debug.println("expon = base (^ <PLUS> base)+ :: "+(argStack.peek().toString()));
                }
        if (jj_2_20(50)) {
          ;
        } else {
          break label_7;
        }
      }
    } else if (jj_2_28(50)) {
      jj_consume_token(RAD);
      if (jj_2_21(50)) {
        jj_consume_token(18);
        oe();
        jj_consume_token(19);
                base = (Expression)(argStack.pop());
                argStack.push(base.squareroot());
                if(Debug.getDebugging()){
                        Debug.println("expon = |'(' oe ')' :: " + (argStack.peek().toString()));
                }
      } else if (jj_2_22(50)) {
        jj_consume_token(20);
        oe();
        jj_consume_token(21);
                base = (Expression)(argStack.pop());
                argStack.push(base.squareroot());
                if(Debug.getDebugging()){
                        Debug.println("expon = |'[' oe ']' :: " + (argStack.peek().toString()));
                }
      } else if (jj_2_23(50)) {
        variable();
                base = (Expression)(argStack.pop());
                argStack.push(base.squareroot());
                if(Debug.getDebugging()){
                        Debug.println("expon = |variable :: " + (argStack.peek().toString()));
                }
      } else if (jj_2_24(50)) {
        number();
                base = (Expression)(argStack.pop());
                argStack.push(base.squareroot());
                if(Debug.getDebugging()){
                        Debug.println("expon = |number :: " + (argStack.peek().toString()));
                }
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } else if (jj_2_29(50)) {
      jj_consume_token(22);
      oe();
      jj_consume_token(19);
                base = (Expression)(argStack.pop());
                argStack.push(base.squareroot());
                if(Debug.getDebugging()){
                        Debug.println("expon = sqrt(oe) :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_30(50)) {
      jj_consume_token(23);
      oe();
      jj_consume_token(24);
      termOrCoeff();
      jj_consume_token(19);
                ex = (Expression)(argStack.pop());
                base = (Expression)(argStack.pop());
                argStack.push(base.root(ex));
                if(Debug.getDebugging()){
                        Debug.println("expon = root(oe,termOrCoeff) :: "+(argStack.peek().toString()));
                }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void variable() throws ParseException {
        Token varToken;
    if (jj_2_31(50)) {
      varToken = jj_consume_token(VARIABLE);
                argStack.push(makeLitOrVarExpr(varToken.image));
                if(Debug.getDebugging()){
                        Debug.println("variable = <VARIABLE> :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_32(50)) {
      constant();
                        if(Debug.getDebugging()){
                                Debug.println("variable = constant() :: "+(argStack.peek().toString()));
                        }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void constant() throws ParseException {
    Token constToken;
    constToken = jj_consume_token(PI);
        argStack.push(new ConstantExpression("pi","<cn type='constant'>&pi;</cn>",Math.PI));
                if(Debug.getDebugging()){
                        Debug.println("constant = pi :: " + (argStack.peek().toString()));
                }
  }

  static final public void number() throws ParseException {
        Token numToken;
        Token denToken;
    numToken = jj_consume_token(CONSTANT);
                try {
                //argStack.push(new NumberExpression((Double.valueOf(NumberExpression.stripCommas(numToken.image))).doubleValue()));
                        argStack.push(new NumberExpression(numToken.image));
            }   catch (NumberFormatException ee) {
                        if(Debug.getDebugging()){
                        Debug.println("bad number...");
                        }
                                argStack.push(new BadExpression());
                }
                if(Debug.getDebugging()){
                        Debug.println("number = <CONSTANT> :: "+(argStack.peek().toString()));
                }
  }

  static final public void stdOp() throws ParseException {
    if (jj_2_33(50)) {
      oeOp();
                if(Debug.getDebugging()){
                        Debug.println("stdOp = oeOp :: "+(argStack.peek().toString()));
                }
    } else if (jj_2_34(50)) {
      mdOp();
                if(Debug.getDebugging()){
                        Debug.println("stdOp = mdOp :: "+(argStack.peek().toString()));
                }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void oeOp() throws ParseException {
        Token op;
    if (jj_2_35(50)) {
      op = jj_consume_token(PLUS);
    } else if (jj_2_36(50)) {
      op = jj_consume_token(MINUS);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                argStack.push(op);
                if(Debug.getDebugging()){
                        Debug.println("oeOp = <PLUS> or <MINUS> :: "+(argStack.peek().toString()));
                }
  }

  static final public void mdOp() throws ParseException {
        Token op;
    if (jj_2_37(50)) {
      op = jj_consume_token(MULTIPLY);
    } else if (jj_2_38(50)) {
      op = jj_consume_token(DIVIDE);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
                argStack.push(op);
                if(Debug.getDebugging()){
                        Debug.println("mdOp = <MULTIPLY> or <DIVIDE> :: "+(argStack.peek().toString()));
                }
  }

  static final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_1();
    jj_save(0, xla);
    return retval;
  }

  static final private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_2();
    jj_save(1, xla);
    return retval;
  }

  static final private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_3();
    jj_save(2, xla);
    return retval;
  }

  static final private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_4();
    jj_save(3, xla);
    return retval;
  }

  static final private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_5();
    jj_save(4, xla);
    return retval;
  }

  static final private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_6();
    jj_save(5, xla);
    return retval;
  }

  static final private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_7();
    jj_save(6, xla);
    return retval;
  }

  static final private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_8();
    jj_save(7, xla);
    return retval;
  }

  static final private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_9();
    jj_save(8, xla);
    return retval;
  }

  static final private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_10();
    jj_save(9, xla);
    return retval;
  }

  static final private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_11();
    jj_save(10, xla);
    return retval;
  }

  static final private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_12();
    jj_save(11, xla);
    return retval;
  }

  static final private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_13();
    jj_save(12, xla);
    return retval;
  }

  static final private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_14();
    jj_save(13, xla);
    return retval;
  }

  static final private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_15();
    jj_save(14, xla);
    return retval;
  }

  static final private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_16();
    jj_save(15, xla);
    return retval;
  }

  static final private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_17();
    jj_save(16, xla);
    return retval;
  }

  static final private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_18();
    jj_save(17, xla);
    return retval;
  }

  static final private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_19();
    jj_save(18, xla);
    return retval;
  }

  static final private boolean jj_2_20(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_20();
    jj_save(19, xla);
    return retval;
  }

  static final private boolean jj_2_21(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_21();
    jj_save(20, xla);
    return retval;
  }

  static final private boolean jj_2_22(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_22();
    jj_save(21, xla);
    return retval;
  }

  static final private boolean jj_2_23(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_23();
    jj_save(22, xla);
    return retval;
  }

  static final private boolean jj_2_24(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_24();
    jj_save(23, xla);
    return retval;
  }

  static final private boolean jj_2_25(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_25();
    jj_save(24, xla);
    return retval;
  }

  static final private boolean jj_2_26(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_26();
    jj_save(25, xla);
    return retval;
  }

  static final private boolean jj_2_27(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_27();
    jj_save(26, xla);
    return retval;
  }

  static final private boolean jj_2_28(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_28();
    jj_save(27, xla);
    return retval;
  }

  static final private boolean jj_2_29(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_29();
    jj_save(28, xla);
    return retval;
  }

  static final private boolean jj_2_30(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_30();
    jj_save(29, xla);
    return retval;
  }

  static final private boolean jj_2_31(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_31();
    jj_save(30, xla);
    return retval;
  }

  static final private boolean jj_2_32(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_32();
    jj_save(31, xla);
    return retval;
  }

  static final private boolean jj_2_33(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_33();
    jj_save(32, xla);
    return retval;
  }

  static final private boolean jj_2_34(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_34();
    jj_save(33, xla);
    return retval;
  }

  static final private boolean jj_2_35(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_35();
    jj_save(34, xla);
    return retval;
  }

  static final private boolean jj_2_36(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_36();
    jj_save(35, xla);
    return retval;
  }

  static final private boolean jj_2_37(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_37();
    jj_save(36, xla);
    return retval;
  }

  static final private boolean jj_2_38(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    boolean retval = !jj_3_38();
    jj_save(37, xla);
    return retval;
  }

  static final private boolean jj_3_11() {
    if (jj_3R_14()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3_8()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_25()) {
    jj_scanpos = xsp;
    if (jj_3_26()) {
    jj_scanpos = xsp;
    if (jj_3_27()) {
    jj_scanpos = xsp;
    if (jj_3_28()) {
    jj_scanpos = xsp;
    if (jj_3_29()) {
    jj_scanpos = xsp;
    if (jj_3_30()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_25() {
    if (jj_3R_16()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    if (jj_3_18()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_18()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  static final private boolean jj_3_30() {
    if (jj_scan_token(23)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_17()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(24)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_11()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(19)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_10() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_11()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_35() {
    if (jj_scan_token(PLUS)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_35()) {
    jj_scanpos = xsp;
    if (jj_3_36()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_13() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_9()) {
    jj_scanpos = xsp;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3_11()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_9() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_11()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_17() {
    if (jj_3R_14()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_34() {
    if (jj_3R_10()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_16() {
    if (jj_3R_18()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_33() {
    if (jj_3R_8()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_29() {
    if (jj_scan_token(22)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_17()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(19)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_4() {
    if (jj_3R_12()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_15() {
    if (jj_scan_token(20)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_17()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(21)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_6() {
    if (jj_3R_13()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_11() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_5() {
    if (jj_3R_12()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_4()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  static final private boolean jj_3R_16() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_14()) {
    jj_scanpos = xsp;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3_16()) {
    jj_scanpos = xsp;
    if (jj_3_17()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_14() {
    if (jj_scan_token(18)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_17()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(19)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_24() {
    if (jj_3R_14()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_14() {
    if (jj_scan_token(CONSTANT)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_3() {
    if (jj_3R_12()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_23() {
    if (jj_3R_18()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_2() {
    if (jj_3R_10()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_11()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_13() {
    if (jj_3R_16()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_22() {
    if (jj_scan_token(20)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_17()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(21)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_21() {
    if (jj_scan_token(18)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_17()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(19)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_12() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_12()) {
    jj_scanpos = xsp;
    if (jj_3_13()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_12() {
    if (jj_3R_15()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_9() {
    if (jj_3R_11()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_2()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_3()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  static final private boolean jj_3_28() {
    if (jj_scan_token(RAD)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_21()) {
    jj_scanpos = xsp;
    if (jj_3_22()) {
    jj_scanpos = xsp;
    if (jj_3_23()) {
    jj_scanpos = xsp;
    if (jj_3_24()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_20() {
    if (jj_scan_token(EXP)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(PLUS)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_16()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_19() {
    if (jj_scan_token(PI)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_38() {
    if (jj_scan_token(DIVIDE)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_27() {
    if (jj_3R_16()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    if (jj_3_20()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_20()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  static final private boolean jj_3_32() {
    if (jj_3R_19()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_1() {
    if (jj_3R_8()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_9()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_8() {
    if (jj_3R_12()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_19() {
    if (jj_scan_token(EXP)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_scan_token(MINUS)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_16()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_7() {
    if (jj_3R_10()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_12()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_18() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_31()) {
    jj_scanpos = xsp;
    if (jj_3_32()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_31() {
    if (jj_scan_token(VARIABLE)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3R_17() {
    if (jj_3R_9()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_1()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  static final private boolean jj_3_37() {
    if (jj_scan_token(MULTIPLY)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_36() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_26() {
    if (jj_3R_16()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    Token xsp;
    if (jj_3_19()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_19()) { jj_scanpos = xsp; break; }
      if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    }
    return false;
  }

  static final private boolean jj_3R_10() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_37()) {
    jj_scanpos = xsp;
    if (jj_3_38()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    } else if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static final private boolean jj_3_18() {
    if (jj_scan_token(EXP)) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    if (jj_3R_16()) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) return false;
    return false;
  }

  static private boolean jj_initialized_once = false;
  static public SMTokenManager token_source;
  static public Token token, jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static public boolean lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[0];
  static final private int[] jj_la1_0 = {};
  static final private JJCalls[] jj_2_rtns = new JJCalls[38];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  public SM(CharStream stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = new SMTokenManager(stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static public void ReInit(CharStream stream) {
    SMTokenManager.ReInit(stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public SM(SMTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(SMTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = SMTokenManager.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = SMTokenManager.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    return (jj_scanpos.kind != kind);
  }

  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = SMTokenManager.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  static final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = SMTokenManager.getNextToken();
    }
    return t;
  }

  static final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=SMTokenManager.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.Vector jj_expentries = new java.util.Vector();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration entriesEnum = jj_expentries.elements(); entriesEnum.hasMoreElements();) {
        int[] oldentry = (int[])(entriesEnum.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  static final public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[25];
    for (int i = 0; i < 25; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 25; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static final public void enable_tracing() {
  }

  static final public void disable_tracing() {
  }

  static final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 38; i++) {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
            case 19: jj_3_20(); break;
            case 20: jj_3_21(); break;
            case 21: jj_3_22(); break;
            case 22: jj_3_23(); break;
            case 23: jj_3_24(); break;
            case 24: jj_3_25(); break;
            case 25: jj_3_26(); break;
            case 26: jj_3_27(); break;
            case 27: jj_3_28(); break;
            case 28: jj_3_29(); break;
            case 29: jj_3_30(); break;
            case 30: jj_3_31(); break;
            case 31: jj_3_32(); break;
            case 32: jj_3_33(); break;
            case 33: jj_3_34(); break;
            case 34: jj_3_35(); break;
            case 35: jj_3_36(); break;
            case 36: jj_3_37(); break;
            case 37: jj_3_38(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  static final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
