/* Generated By:JavaCC: Do not edit this line. SMConstants.java */
package edu.cmu.old_pact.cmu.sm;

public interface SMConstants {

  int EOF = 0;
  int EOL = 4;
  int PLUS = 5;
  int MINUS = 6;
  int MULTIPLY = 7;
  int DIVIDE = 8;
  int EXP = 9;
  int RAD = 10;
  int CONSTANT = 11;
  int FLOAT = 12;
  int INTEGER = 13;
  int TRIINT = 14;
  int DIGIT = 15;
  int VARIABLE = 16;
  int PI = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "<RAD>",
    "<CONSTANT>",
    "<FLOAT>",
    "<INTEGER>",
    "<TRIINT>",
    "<DIGIT>",
    "<VARIABLE>",
    "<PI>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"sqrt(\"",
    "\"root(\"",
    "\",\"",
  };

}
