//////////////////////////////////////////////////////
//		CTAT Interface Editor Documentation			//
//													//
//////////////////////////////////////////////////////

***The Menu Bar***

-FILE
	|--> New File: Create a new blank interface file.  The initial contents
	|		of the file are designated by creation_template.html
	|--> Open File: Open the filepicker dialog window to choose a file from
	|		Google Drive to open in the editor.  Only files that have been
	|		created with the editor can be opened this way.
	|--> Save File: Save the file currently open in the editor to Google
	|		Drive.  The saved file will still contain all of the elements
	|		used by the editor to manipulate the DOM (e.g. resize handles),
	|		and so should not be loaded outside of the editor.  If a file
	|		already exists in the destination folder with the same name as
	|		that chosen to save the file under, the existing file will be
	|		overwritten.
	|--> Save As: Equivalent to 'Save File'
	|--> Publish: Export the file so it can be loaded outside of the editor.
	|		Creates a new directory inside the destination directory.  The
	|		new directory will contain the interface HTML file as well as 
	|		a directory named 'assets', in which a CSS file containing the
	|		style rules generated by the editor will be created.  All 
	|		external files needed by the interface (e.g. images, stylesheets)
	|		should be copied into the 'assets' directory before deployment.  
	|		HTML files created by the 'Publish' operation will no longer be
	|		modifiable by the editor.
	|--> Settings:
	|--> Close File: Equivalent to 'New File'

-EDIT
	|--> Copy: Copy the currently selected DOM element(s) to the clipboard
	|--> Paste: Paste the contents of the clipboard onto the working file
	|--> Undo: Undo the most recent modification to the working file
	|--> Redo: Redo the most recently undid modification to the working file
	|--> Delete Selection: Remove the currently selected DOM element(s)
	|		from the file
	|--> [Disable|Enable] Snap to Grid:  Toggle the behavior of elements
	|		being dragged.  When enabled, elements will only move in
	|		increments of 20px.  When disabled, elements will move freely.
	|		(Enabled by default)
	|--> Bring to Front: Set the currently selected element(s) as highest
	|		in the DOM stack order.
	|--> Bring forward: Set the currently selected element(s) as one level
	|		higher in the DOM stack order.
	|--> Bring backward: Set the currently selected element(s) as one level
	|		lower in the DOM stack order.
	|--> Send to Back: Set the currently selected element(s) as lowest in
			the DOM stack order.

-VIEW
	|--> Demonstrate Tutor: Load the currently opened interface in the demo
	|	window and connect to the authoring tools (behavior recorder).
	|	The authoring tools must be running locally prior to running this
	|	operation.  Also, the connection to tutordesk must not be running
	|	over HTTPS; only HTTP will allow an unsecured connection between the
	|	browser and the authoring tools.
	|--> [Show|Hide] Tab Order: Toggle whether or not the tab order (order
		in which components will gain focus when the tab key is pressed)
		is displayed in the editor.  (Hidden by default)

-INSERT
	|--> Text box: Add a text box to the interface.  Text boxes are non-
	|	interactive blocks of arbitrary text.  Double-clicking a text box
	|	will allow editing its content.
	|--> Image: Add an image to the interface.  Images can be linked via
	|	URL or loaded from Google Drive.  Images loaded from Google Drive
	|	will need to be copied into the 'assets' directory to be found by
	|	the interface after publishing.
	|--> Container: Add a container (div) element to the interface.
	|--> CTAT Component: Add a CTAT tutor component to the interface.
	|	(See 'CTAT Components' section for component descriptions)
	|--> Question Template: Add a pre-fab group of components to the
	|	interface representing a certain type of question or problem
	|--> Custom Stylesheet: Import a stylesheet from Google Drive.
		Stylesheets loaded this way will need to be copied into the
		'assets' directory to be found by the interface after publishing

-HELP


*** Icon Menu ***

(Operations are listed in order from left to right)

-Save: See File->Save File in the File menu section

-Undo: See Edit->Undo in the Menu Bar section

-Redo: See Edit->Redo in the Menu Bar section

-Insert Text Box: See Insert->Text box in the Menu Bar section

-Insert Image: See Insert->Image in the Menu Bar section

-Insert Container: See Insert->Container in the Menu Bar section

-Delete: See Edit->Delete selection in the Menu Bar section

-Copy: See Edit->Copy in the Menu Bar section

-Paste: See Edit->Paste in the Menu Bar section

-Top: See Edit->Bring to front in the Menu Bar section

-Up: See Edit->Bring forward in the Menu Bar section

-Down: See Edit->Bring backward in the Menu Bar section

-Bottom: See Edit->Send to Bottom in the Menu Bar section

-Demonstrate: See View->Demonstrate Tutor in the Menu Bar section


*** The Property Tool ***

The property tool is used to control the appearance and behavior of
individual components.  Its inputs are populated based on the currently
selected element.

-The 'Attributes' pane: This pane displays CTAT-specific attributes that
	can be set on the currently selected component.  See the CTAT Components
	section for descriptions of the possible attributes for each component.

-The 'Colors' pane: This pane allows you to change the foreground and
	background colors of the currently selected component.  When a text-
	based element is selected, foreground color will affect the font color.
	The 'background image' button will bring up a dialog allowing you to
	choose an image (by URL or Google Drive) to use as the background of the
	selected element.  Note that only Google Drive allows image imports; if
	you are using either of the other cloud services you will only be able
	to link images by URL.
	
-The 'Border' pane: This pane allows you to control the appearance of the
	selected element's border.  Note that both the 'width' and 'style' inputs
	must be set for the element's border to be visible.
	
-The 'Position' pane: This pane allows you to explicitly set the position of
	the selected element.  The distances are relative to the element's immediate
	parent.
	

	
	
*** CTAT Components ***	

---Attributes Common to Multiple Component Types---

-ID: Sets the "id" attribute of the selected element.  The IDs of CTAT Components
	must be unique, and can't be either of the values "done" or "hint"

-Enabled: if checked, the component will be interactive when the tutor is run

-Graded:

-Show Feedback: if checked, grading feedback will be shown on the component.

-Show Highlight: if checked, the component will be highlighted when a hint is requested
	for that step.

-Disable on Correct: if checked, the component will become non-interactive once the
	correct value has been entered.

-Font Size: Sets the font size (in px) of the component.

-Tab Order: Determines the order in which components will gain focus when the tab key
	is pressed.  Lower values will gain focus before higher values.  To display the
	tab order of all components in the interface, open the 'View' menu on the menu bar
	and click 'Show Tab Order'.  Note that this will only display tab order values that
	have been explicitly set through the Attributes pane.
	
-Label: Sets the display text on a component.

-Value (Unit Display): Sets the value for unit display components (Pie Chart and Fraction Bar).
	The value should be formatted as a summation of fractions (e.g. "1/2+1/4+(0*1/8)").
	Each fraction will constitute one 'piece' in the component.  Fractions multiplied
	by zero will be displayed as de-selected.
	
-Group Name: Sets the name of the group to which the selected component belongs.
	Components with the same group name will be graded together; for example, you can 
	use this property to denote groups of CTATRadioButtons that are part of the same problem.

---Component Descriptions---

-Text Input: A text box for single-line inputs.  Double-clicking on the element
	will allow you to edit its content.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct,
		Font Size, Tab Order.
		
	-Text Input Specific Attributes:
		Max Length: Sets the max number of characters that can be input into the component.
		
		Has Initial Focus: if checked, the component will have focus at the time the tutor
			is run.

-Text Area: A text box for multi-line inputs.  Double-clicking on the element will allow
	you to edit its content.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct,
		Font Size, Tab Order.
		
	-Text Area Specific Attributes:
		Tab on Enter: if checked, pressing the 'enter' key while the component has
			focus will be equivalent to pressing 'tab', that is, focus will switch to the
			next component in the tab order.  If not checked, pressing 'enter' will create
			a newline in the component's contents.

-Text Field: 

-Table: A grid of Text Areas.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct.
	
	-Table Specific Attributes:
		Row Count: The number of rows in the table.
		
		Column Count: The number of columns in the table.

-Pie Chart: A graphical representation of a fraction or set of fractions, in the shape
	of a circle.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct,
		Value (Unit Display).
	
	-Pie Chart Specific Attributes:
		Shadow Length: A number indicating the displacement distance of each wedge's drop shadow.
			Set to 0 to disable the drop shadows.

		Spread Distance: The number of pixels that each wedge should be displaced from the center
			of the chart. This has the effect of spacing the wedges from each other.

-Fraction Bar: A graphical representation of a fraction or set of fractions, in the shape of
	a rectangle.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct,
		Value (Unit Display).
		
	-This component has no unique attributes
	
-Number Line: A number line with customizable range and increments.

	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct.
	
	-Number Line Specific Attributes:
		Max Value: The maximum value on the number line.
		Min Value: The minimum value on the number line.
		Large Increment: The value between each large tick mark on the numberline.
			Set to '0' to disable large tick marks.
		Small Increment: The value between each small tick mark on the numberline.
			Set to '0' to disable small tick marks.
		Number of Points: The maximum number of points that can be set on the numberline.
		Point Size: The size in pixels of each point on the numberline.
		Snap to Tick Marks: If checked, points can only be set on values with corresponding
			tick marks.  If not checked, points can be set anywhere along the line.
		Angle:	The angle in degrees the numberline is rotated from the horizontal.
		
-Radio Button: A labeled radio button.  Only one radio button per group can be selected.

	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct, Label,
		Group Name.
		
	-This component has no unique attributes.
	
-Check Box: A labeled checkbox.  Any number of checkboxes per group can be selected.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct, Label.

	-This component has no unique attributes.

-Combo Box: A dropdown list of customizable options.  Options can be set through the Attribute
	Pane.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct, 
		Font Size.
	
	Combo Box Specific Attributes:
		Number of Options: Specifies the number of available options in the drop down list.
			A corresponding number of inputs will appear in the attributes pane which can
			then be used to set the values of the options themselves.
	
-DragNDrop: A container element that can be used to create sorting problems.  Typically such
	a problem will consist of two DragNDrop components which share a group name, with one
	acting as the source container and the other acting as the destination.  To populate the
	source, simply drag the components you want to be sorted onto the source container.  Use
	only non-interactive elements, such as blocks of text or images.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct,
		Group Name.
	
	-DragNDrop Specific Attributes:
		Max # of Items: Specifies the maximum number of items that can be dropped into the
			component.

-Button: A generic button element
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct, Label,
		Tab Order.
	
	-Button Specific Attributes: 
		Value (Button):  Sets the value to be used as the input of the SAI the button produces 
		when it is clicked. Default is "-1". In most cases, you will not need to change this.
		It becomes useful when using the button in conjunction with a component that has 
		data-ctat-ctrl-* attributes.

Submit Button: A button element that can be used to trigger grading on a component or group of
	components.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct, Label,
		Tab Order.
		
	-Submit Button Specific Attributes:
		Target ID: Specifies the ID of the component to trigger grading for.  Multiple components
			can be triggered by setting this to a semicolon-separated list of IDs.
		
-Audio Button: A button that can be used to play audio from the tutor.
	
	-Shared Attributes: ID, Enabled, Show Feedback, Show Highlight, Disable on Correct, Label,
		Tab Order.
	
	-Audio Button Specific Attributes:
		Source URL: Specifies the url of the audio file that clicking the button will trigger.

-Hint Widget: A grouping of three commonly-used components (Hint Window, Hint Button, and
	Done Button).
	
	-Shared Attributes: ID
	
	-Hint Widget Specific Attributes:
		Hints Enabled: If checked, users of the tutor will be able to request hints by clicking
			the hint button.
		Done Button Enabled: If checked, users will be able to signal to the tutor that they are
			done by clicking the done button.