package SubtractionTutor;

/*
 * TutorInterface.java
 *
 * Created on April 23, 2003, 12:06 PM
 */
import javax.swing.JPanel;

import edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Launcher;

/**
 *
 * @author  sanket
 */
public class TutorInterface extends JPanel {
    
    /** Creates new form TutorInterface */
    public TutorInterface() {
        super();
        initComponents();
        setSize(300, 320);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        cTAT_Options1 = new edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options();
        table1 = new pact.CommWidgets.JCommTable();
        jLabel1 = new javax.swing.JLabel();

        cTAT_Options1.setInterfaceHeight(399);
        cTAT_Options1.setInterfaceWidth(688);

        setLayout(null);

        table1.setColumns(6);
        table1.setRows(6);
		table1.setCommName("table1");
        add(table1);
        table1.setBounds(50, 60, 249, 129);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 24));
        jLabel1.setText("-");
        add(jLabel1);
        jLabel1.setBounds(30, 140, 20, 30);

    }
    // </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new CTAT_Launcher(args).launch(new TutorInterface());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options cTAT_Options1;
    private javax.swing.JLabel jLabel1;
    private pact.CommWidgets.JCommTable table1;
    // End of variables declaration//GEN-END:variables
}
