# Generated by Django 2.2 on 2019-04-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='student_name',
            new_name='tutee_name',
        ),
    ]
