# Generated by Django 2.2 on 2019-10-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190408_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('problem_type', models.IntegerField()),
                ('problem_rating', models.IntegerField()),
            ],
        ),
    ]
