# Generated by Django 2.2 on 2019-10-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_problembank'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsUnderTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
            ],
            options={
                'ordering': ('questions',),
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.TextField()),
                ('all_questions', models.ManyToManyField(to='chat.QuestionsUnderTypes')),
            ],
            options={
                'ordering': ('question_type',),
            },
        ),
    ]
