# Generated by Django 2.2 on 2019-10-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_questionbank_questionsundertypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='tutoring_phase',
            field=models.IntegerField(choices=[(1, 'Pre'), (2, 'During'), (3, 'Post')], default=1),
        ),
    ]
