# Generated by Django 2.2 on 2019-10-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_questionbank_tutoring_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
