# Generated by Django 2.2 on 2019-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_session_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='image_name',
            field=models.TextField(default='000'),
        ),
    ]
