# Generated by Django 2.2 on 2019-11-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_session_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaHints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunch_id', models.TextField()),
                ('hints', models.TextField()),
                ('help_level', models.TextField(default='1')),
                ('tags', models.TextField()),
            ],
        ),
    ]
