# Generated by Django 2.2 on 2019-11-08 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_metahints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metahints',
            name='bunch_id',
        ),
        migrations.RemoveField(
            model_name='metahints',
            name='help_level',
        ),
    ]
