# Generated by Django 2.2 on 2019-11-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20191108_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dormin_fields', models.TextField()),
                ('dormin_contents', models.TextField()),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_problems', to='chat.Session')),
            ],
        ),
    ]
