# Generated by Django 2.2 on 2019-11-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_workoutproblems'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutproblems',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
