# Generated by Django 2.2 on 2019-11-11 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_workoutproblems_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_actions', to='chat.Session')),
            ],
        ),
    ]
