# Generated by Django 2.2 on 2019-11-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_actionlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogs',
            name='cf_action',
            field=models.TextField(default=''),
        ),
    ]
