# Generated by Django 2.2 on 2019-11-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_actionlogs_cf_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlogs',
            old_name='actions',
            new_name='actions_text',
        ),
    ]
