# Generated by Django 2.2 on 2019-11-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20191111_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogs',
            name='action_tutee',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='action_tutor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='dialogue_from_tutee',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='dialogue_from_tutor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='hint_given',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='hint_requested',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='input_tutee',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='input_tutor',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='new_problem_entered',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='selection_tutee',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='selection_tutor',
            field=models.TextField(default=''),
        ),
    ]
