# Generated by Django 2.2 on 2019-11-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20191118_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogs',
            name='current_equation_state',
            field=models.TextField(default=''),
        ),
    ]
