# Generated by Django 2.2 on 2019-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_actionlogs_current_equation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogs',
            name='action_meta',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='input_meta',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='selection_meta',
            field=models.TextField(default=''),
        ),
    ]
