# Generated by Django 2.2 on 2019-11-21 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20191121_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_contents', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_quiz', to='chat.Session')),
            ],
        ),
    ]
