# Generated by Django 2.2 on 2020-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_quizupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutproblems',
            name='is_correct_step',
            field=models.BooleanField(default=False),
        ),
    ]
