# Generated by Django 2.2 on 2020-01-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_workoutproblems_is_correct_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutproblems',
            name='is_correct_step',
            field=models.TextField(),
        ),
    ]
