# Generated by Django 2.2 on 2020-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20200130_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutproblems',
            name='is_correct_step',
        ),
        migrations.AddField(
            model_name='actionlogs',
            name='is_correct_step',
            field=models.TextField(default=''),
        ),
    ]
