# Generated by Django 2.2 on 2020-02-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_auto_20200130_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainSessionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('global_index', models.TextField(default='')),
                ('correctness_tags', models.TextField(default='aaaaaaaaaaaaaaaaaaaaaa')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_persist_data', to='chat.Session')),
            ],
        ),
    ]
