/*
 * TutorTemplate.java
 *
 * Created on May 27, 2004, 10:27 PM
 */

package edu.cmu.pact.BehaviorRecorder.View;

import javax.swing.JPanel;

import edu.cmu.pact.BehaviorRecorder.Controller.SingleSessionLauncher;

/**
 *
 * @author  sanket
 */
public class TutorInterface extends JPanel {
    
    /** Creates new form TutorInterface */
    public TutorInterface() {
        super();
        initComponents();
        setSize(300, 320);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        table1 = new pact.CommWidgets.JCommTable();
        jLabel1 = new javax.swing.JLabel();
        commLabel1 = new pact.CommWidgets.JCommLabel();

        setLayout(null);

        table1.setColumns(6);
        table1.setCommName("table1");
        add(table1);
        table1.setBounds(50, 30, 230, 140);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 24));
        jLabel1.setText("+");
        add(jLabel1);
        jLabel1.setBounds(30, 100, 20, 30);

        commLabel1.setImageName("include/pact/Connected.gif");  // borrow image from include/ dir
        commLabel1.setCommName("commLabel1");
        add(commLabel1);
        commLabel1.setBounds(210, 220, 110, 30);

    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new SingleSessionLauncher().launch(new TutorInterface());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pact.CommWidgets.JCommLabel commLabel1;
    private javax.swing.JLabel jLabel1;
    private pact.CommWidgets.JCommTable table1;
    // End of variables declaration//GEN-END:variables
    
    pact.CommWidgets.JCommTable getTable() {
        return table1;
    }
    
}
