/*
 * TutorTemplate.java
 *
 * Created on May 27, 2004, 10:27 PM
 */


import javax.swing.JPanel;

import edu.cmu.pact.BehaviorRecorder.Controller.SingleSessionLauncher;

/**
 *
 * @author  sanket
 */
public class CL_LMS_Test_Interface_2 extends JPanel {
    
    /** Creates new form TutorInterface */
    public CL_LMS_Test_Interface_2() {
        super();
        
        initComponents();
        setSize(300, 320);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        cTAT_Options1 = new edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Table0 = new pact.DorminWidgets.DorminTable();

        cTAT_Options1.setEnableLMSLogin(true);
        cTAT_Options1.setInterfaceHeight(420);
        cTAT_Options1.setInterfaceWidth(420);
        cTAT_Options1.setUseDemonstrateMode(false);
        cTAT_Options1.setUsePseudoTutorMode(true);

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("MS Sans Serif", 1, 24));
        jLabel1.setText("+");
        add(jLabel1);
        jLabel1.setBounds(40, 160, 20, 30);

        jLabel2.setFont(new java.awt.Font("MS Sans Serif", 0, 18));
        jLabel2.setText("Interface #2");
        add(jLabel2);
        jLabel2.setBounds(50, 20, 170, 20);

        add(Table0);
        Table0.setBounds(70, 70, 165, 85);

    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new CTAT_Launcher(args).launch(new CL_LMS_Test_Interface_2());
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pact.DorminWidgets.DorminTable Table0;
    private edu.cmu.pact.BehaviorRecorder.Controller.CTAT_Options cTAT_Options1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
}
